Extracted WireHelperService and WireSupport together to a new bundle
eclipse/kura pull request #1047
Opened 2017-01-26 07:33 UTC by amitjoy

More Changes

1. Service Components are delayed
2. Import Package and Require Bundle Fixes in Gogo Shell Command for Wires

2017-01-26 11:22 UTC, amitjoy commented
@MMaiero @cdealti  Could you kindly have a review on this? This has been done to have consistency in the source base as we have already taken more modular approach for helper services.

2017-01-30 11:14 UTC, ctron commented on kura/org.eclipse.kura.wire.helper.provider/about_files/epl-v10.html
> +<?xml version="1.0" encoding="ISO-8859-1" ?>
This file is not needed.

2017-01-31 00:09 UTC, amitjoy commented on kura/org.eclipse.kura.wire.helper.provider/about_files/epl-v10.html
> +<?xml version="1.0" encoding="ISO-8859-1" ?>
Every bundle in Kura contains this license file and that's the reason, it has been kept here as well.

2017-01-31 08:23 UTC, ctron commented on kura/org.eclipse.kura.wire.helper.provider/about_files/epl-v10.html
> +<?xml version="1.0" encoding="ISO-8859-1" ?>
Not every. But still, because it is wrong there is no reason to continue doing so.

2017-02-01 00:48 UTC, amitjoy commented on kura/org.eclipse.kura.wire.helper.provider/about_files/epl-v10.html
> +<?xml version="1.0" encoding="ISO-8859-1" ?>
Agreed 👍

2017-02-01 01:16 UTC, amitjoy commented
Done 👍

2017-02-02 10:07 UTC, amitjoy commented
@ctron Could you kindly have a look on this?

2017-02-02 10:37 UTC, MMaiero requested changes

2017-02-02 10:37 UTC, MMaiero commented on kura/distrib/pom.xml
> +									<groupId>org.eclipse.kura</groupId>
Ok this, but you missed the following move step

2017-02-02 11:16 UTC, amitjoy commented on kura/distrib/pom.xml
> +									<groupId>org.eclipse.kura</groupId>
Done 👍

2017-02-02 11:45 UTC, MMaiero approved these changes

2017-02-02 11:45 UTC, merged