#1067: Tests for org.eclipse.kura.core.cloud
eclipse/kura pull request #1072
Opened 2017-02-02 17:19 UTC by djurod

- Prepared unit tests for CloudClientImpl.
- Fixed an endless recursion in one of the CloudClientImpl.publish()
  methods (parameter topic was missing).
- Removed some of the code duplication in CloudClientImpl class.

Signed-off-by: Djuro Drljaca <djuro.drljaca@comtrade.com>

2017-02-03 10:46 UTC, cdealti requested changes

2017-02-03 10:46 UTC, cdealti commented on kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudClientImpl.java
> +        return publish(options.getTopicClientIdToken(), topic, payload, qos, retain, priority);
nice catch!
Can you please review the implementation and rename all ``topic`` parameters to ``appTopic``. Please check consistency with the CloudService Javadoc.

2017-02-03 12:40 UTC, djurod commented on kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudClientImpl.java
> +        return publish(options.getTopicClientIdToken(), topic, payload, qos, retain, priority);
Fixed

2017-02-07 09:43 UTC, cdealti approved these changes

2017-02-07 09:43 UTC, merged