Heater demo example using Maven/BND.
eclipse/kura pull request #1264
Opened 2017-03-25 17:05 UTC by dwoodard1

@ctron @cdealti I had several people ask me at a recent Eclipse event about pure Maven and BND with Eclipse Kura. I know @ctron has written about this as well. Some are under the impression you must use Eclipse PDE/Tycho tooling in order to write bundles for Eclipse. 

As such, I ported the heater demo to use annotations and the maven BND plugin. I think it would be good to have this example the Kura repo for reference.

2017-03-27 10:46 UTC, ctron commented on kura/examples/bnd_examples/org.eclipse.kura.demo.bnd.heater/src/main/java/org/eclipse/kura/demo/bnd/heater/Heater.java
> +    private static final Logger s_logger = LoggerFactory.getLogger(Heater.class);
Could we use the new style, simply use `logger`, also see other members.

2017-03-27 13:38 UTC, dwoodard1 commented on kura/examples/bnd_examples/org.eclipse.kura.demo.bnd.heater/src/main/java/org/eclipse/kura/demo/bnd/heater/Heater.java
> +    private static final Logger s_logger = LoggerFactory.getLogger(Heater.class);
Yep, will make a commit shortly. I was using IntelliJ to make sure I was avoiding any Eclipse specific tooling. May be nice to include an IntelliJ code formatter that mimics what we have for Eclipse.

2017-03-28 08:24 UTC, markoer approved these changes

2017-03-28 08:24 UTC, markoer commented on kura/examples/bnd_examples/org.eclipse.kura.demo.bnd.heater/pom.xml
> +                        <source>1.7</source>
Maybe go for 1.8, since Kura now uses this version.

2017-03-29 08:47 UTC, ctron commented on kura/examples/bnd_examples/org.eclipse.kura.demo.bnd.heater/src/main/java/org/eclipse/kura/demo/bnd/heater/Heater.java
> +            logger.info("Update - " + s + ": " + properties.get(s));
I just spotted this one... Should better be `Update - {}: {}` ... like a few lines above.

2017-03-29 08:47 UTC, ctron approved these changes

2017-03-31 10:00 UTC, MMaiero commented
@dwoodard1 Why this PR is failing the IP validation?

2017-03-31 13:09 UTC, dwoodard1 commented
@MMaiero I didn't sign the commit.

2017-04-03 08:26 UTC, ctron requested changes

2017-04-03 08:26 UTC, ctron commented on kura/examples/bnd_examples/org.eclipse.kura.demo.bnd.heater/src/main/java/org/eclipse/kura/demo/bnd/heater/Heater.java
> +            logger.error("Cannot publish topic: {}" + topic, e);
That should be:

```java
logger.error("Cannot publish topic: {}", topic, e);
```

2017-04-03 19:02 UTC, MMaiero commented
Could you please squash the commits? Thanks

2017-04-03 21:43 UTC, dwoodard1 commented
Yes, but there's a Squash and Merge option in Github.

2017-04-04 07:43 UTC, ctron approved these changes

2017-04-04 15:50 UTC, merged