JUnit tests org.eclipse.kura.raspberrypi.sensehat
eclipse/kura pull request #1274
Opened 2017-03-28 18:18 UTC by darionct

Created unit tests for sensors.
Created dummy device to simulate HW devices.

KuraI2CDevice.class replaces real implementation of the same name because 
it comes first in the class path when tests are run.
Devices are simulated with dummy implementation which returns 
and stores values using the "register" variable.

Signed-off-by: Dario Novakovic <dario.novakovic@comtrade.com>

2017-03-30 15:18 UTC, cdealti commented
OK to merge it.

2017-03-30 15:53 UTC, cdealti requested changes

2017-03-30 15:53 UTC, cdealti commented on kura/test/org.eclipse.kura.raspberrypi.sensehat.test/src/test/java/org/eclipse/kura/raspberrypi/sensehat/sensors/HTS221Test.java
> +     * public void testIsHumidityReady() {
@darionct please enable this as PR #1271 has been already merged

2017-03-31 11:47 UTC, MMaiero commented
@darionct Please perform a rebase instead of a merge when you have to align your branches. Also try to shape your commits to self-contained ones, in order that the code always builds. Thanks

2017-03-31 12:13 UTC, darionct commented
Mateo,


I know that #1274 is a mess, but i never wanted to do it, git led me that way.


Have you got any idea how to fix this? I tried squashing but its not working because of this last "merged commit".



I understand your point, will do next time. Is there anything we can do now?



________________________________
From: MMaiero <notifications@github.com>
Sent: Friday, March 31, 2017 13:47
To: eclipse/kura
Cc: Dario Novaković; Mention
Subject: Re: [eclipse/kura] JUnit tests org.eclipse.kura.raspberrypi.sensehat (#1274)


@darionct<https://github.com/darionct> Please perform a rebase instead of a merge when you have to align your branches. Also try to shape your commits to self-contained ones, in order that the code always builds. Thanks

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/eclipse/kura/pull/1274#issuecomment-290691355>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AZKCw1jlEdrgpyKX98nnljaIZ6loDz2Rks5rrOe1gaJpZM4MsAMy>.

2017-04-02 12:57 UTC, closed without merging

2017-04-02 13:00 UTC, darionct commented
Closing due to the git merging wen wrong. Replacement PR will be created.