Uniformed DataTypes to match the ones supported by kura protobuf.
eclipse/kura pull request #1296
Opened 2017-04-04 19:48 UTC by MMaiero

Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

2017-04-04 22:14 UTC, amitjoy commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/type/TypedValue.java
>   * @see ShortValue
Remove `ShortValue` as well

2017-04-04 22:19 UTC, amitjoy requested changes
Minor Change Requests

2017-04-04 22:19 UTC, amitjoy commented on kura/org.eclipse.kura.asset.cloudlet.provider/src/main/java/org/eclipse/kura/internal/asset/cloudlet/AssetCloudlet.java
> +                value = TypedValues.newFloatValue(Byte.parseByte(userValue));
`Float.parseFloat`

2017-04-05 09:12 UTC, MMaiero commented
As stated in HSQLDB only DOUBLE is the result of a query. I've not found a simple way to keep floats after a query.
I think that, for the database, we must point out that in the documentation. For the rest of the components (asset, publisher, etc) everything seems fine.

2017-04-05 09:12 UTC, MMaiero commented
Closes #1295

2017-04-05 09:23 UTC, MMaiero commented
Closes #1294

2017-04-05 10:55 UTC, amitjoy requested changes

2017-04-05 10:55 UTC, amitjoy commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/type/FloatValue.java
>       * Instantiates a new byte value.
new float value

2017-04-05 11:52 UTC, MMaiero commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/type/FloatValue.java
>       * Instantiates a new byte value.
Done

2017-04-05 12:49 UTC, amitjoy approved these changes

2017-04-05 12:51 UTC, merged