DataService enhancement with database indexing
eclipse/kura pull request #1308
Opened 2017-04-07 14:12 UTC by ymai

Include additional indexing to DataStore to reduce the amount of time for query data for deletion during housekeeping

2017-04-07 14:21 UTC, cdealti commented
@ymai you need to sign the [ECA](https://www.eclipse.org/legal/ECA.php) at Eclipse

2017-04-07 14:26 UTC, cdealti requested changes

2017-04-07 14:26 UTC, cdealti commented on kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/data/store/DbDataStore.java
> +		// Introduced in 2.0.4, create index for fluke_messages
Please remove this

2017-04-07 14:26 UTC, cdealti commented on kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/data/store/DbDataStore.java
> +        // Introduced in 3.0??.  create index that speeds up the process of deleting expired messages during housekeeping task
Please remove this

2017-04-07 14:27 UTC, cdealti requested changes

2017-04-07 14:27 UTC, cdealti commented on kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/data/store/DbDataStore.java
> +        // Introduced in 3.0??.  create index that speeds up the process of deleting expired messages during housekeeping task
Please also update the copyright header:

Copyright (c) 2011, 2017 Eurotech and/or its affiliates

2017-04-07 16:03 UTC, cdealti commented
@ymai have you signed the ECA with the same email used to signoff the commit?

2017-04-08 12:21 UTC, dwoodard1 commented
@ymai @cdealti I am not sure why the check is failing. I have verified using [this lookup tool](https://projects.eclipse.org/user/cla/validate) that the email address used to sign the commit is valid. I think if you update your reviews we can merge.

2017-04-08 21:31 UTC, ymai commented
Hi @cdealti,  It is signed now with my eclipse account.

2017-04-10 11:55 UTC, cdealti commented
This has been manually merged after rewording the commit message.

2017-04-10 11:55 UTC, closed without merging