Proposal for Wires Script Filter
eclipse/kura pull request #1324
Opened 2017-04-12 12:49 UTC by nicolatimeus

Adds a new wire component that allows to perform filtering operations on wire envelopes using Javascript code, executed by the Nashorn engine.
The script is provided as a configuration property and is executed every time an envelope is received by the component, the script can access the received envelope and can emit arbitrary wire records.
Each ScriptFilter component instance maintains a separate Javascript context which is persisted across different wire receive events, this allows to implement operations that require a persistent state (for example a counter).

Signed-off-by: nicolatimeus <nicola.timeus@eurotech.com>

2017-04-12 13:25 UTC, amitjoy commented
Is there any specific reason of having it in a complete different bundle?

2017-04-12 13:32 UTC, nicolatimeus commented
This PR is a proof of concept, the bundles are not even included in the build for now. After some testing we can decide how to package this. It can be included in `org.eclipse.kura.wire.component.provider` or published as a Marketplace dp.

2017-06-16 10:33 UTC, cdealti commented
@amitjoy can you please review?

2017-06-16 12:06 UTC, amitjoy commented
If it is going to be in the distribution, I believe it would be good to have it packaged in `org.eclipse.kura.wire.component.provider`.

@nicolatimeus What's your opinion on this?

2017-06-19 14:47 UTC, nicolatimeus commented
Maybe it could be better to provide this component in a deployment package.
Adding this to the distribution would mean electing Javascript as a privileged scripting language for the wires.
Other components that provide script functionality using different languages can be added in future, if these components are distributed in dps the user can choose the preferred one.

@amitjoy what do you think?

2017-06-20 12:53 UTC, amitjoy commented
@nicolatimeus I like the idea. 👍

2017-06-22 07:42 UTC, amitjoy requested changes
Some minor ones

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.localization/build.properties
> +source.. = src/
Could you make it consistent with the other bundles? `src/main/java`

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.localization/src/org/eclipse/kura/wire/script/filter/localization/ScriptFilterMessages.java
> + * Contributors:
We can remove contributors here

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/OSGI-INF/ScriptFilter.xml
> +<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" activate="activate" configuration-policy="require" deactivate="deactivate" enabled="true" immediate="false" modified="updated" name="or
This is a service consumer and therefore, `immediate` should be set to true

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/build.properties
> +source.. = src/
`src/main/java`

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/src/org/eclipse/kura/wire/script/filter/provider/ScriptFilter.java
> + * Contributors:
We can remove this

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/src/org/eclipse/kura/wire/script/filter/provider/WiresScriptInterface.java
> +            return null;
better off with `Optional`

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/src/org/eclipse/kura/wire/script/filter/provider/WiresScriptInterface.java
> +            return null;
`Optional`

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/src/org/eclipse/kura/wire/script/filter/provider/WiresScriptInterface.java
> +        return outputRecords;
return immutable view

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/src/org/eclipse/kura/wire/script/filter/provider/WiresScriptInterface.java
> +        public OutputWireRecordInterface putBoolean(String key, boolean value) {
Instead of having methods for every types, you can use only one method, namely `put(String, boolean)` and use `TypedValues#newTypedValue(Object)`

2017-06-22 07:42 UTC, amitjoy commented on kura/org.eclipse.kura.wire.script.filter.provider/META-INF/MANIFEST.MF
> +Bundle-Name: org.eclipse.kura.wire.script.filter.provider
I believe we can provide an user-friendly name

2017-06-27 15:59 UTC, MMaiero commented
@nicolatimeus Is this PR complete and ready to be merged? (Apart the travis conflict?)

2017-06-28 08:02 UTC, nicolatimeus commented
Yes, it should be ready

2017-06-28 10:09 UTC, MMaiero commented on kura/org.eclipse.kura.wire.script.filter.localization/META-INF/MANIFEST.MF
> +Bundle-RequiredExecutionEnvironment: JavaSE-1.6
Very minor: since the host runs on Java 8, I would expect Java 8 also for the fragment

2017-06-28 10:20 UTC, MMaiero commented on kura/org.eclipse.kura.wire.script.filter.localization/META-INF/MANIFEST.MF
> +Fragment-Host: org.eclipse.kura.localization;bundle-version="1.0.0"
Probably we could have it as a range?

2017-06-28 10:21 UTC, MMaiero commented on kura/org.eclipse.kura.wire.script.filter.localization/META-INF/MANIFEST.MF
> +Fragment-Host: org.eclipse.kura.localization;bundle-version="1.0.0"
And develop, now, is distributing localization 1.0.100

2017-06-28 10:27 UTC, MMaiero commented on kura/org.eclipse.kura.wire.script.filter.provider/src/main/java/org/eclipse/kura/wire/script/filter/provider/ScriptFilter.java
> +    private CompiledScript script;
I would move this variable after all the static variables

2017-06-28 11:55 UTC, MMaiero commented
Please also apply the cleanup profile to all the source code.

2017-06-28 12:21 UTC, MMaiero approved these changes

2017-06-28 12:22 UTC, merged