Fixed factory components not being created from uploaded snapshot
eclipse/kura pull request #1364
Opened 2017-05-05 15:58 UTC by nicolatimeus

Signed-off-by: nicolatimeus <nicola.timeus@eurotech.com>

2017-05-05 16:03 UTC, amitjoy commented on kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurationServiceImpl.java
> +                    logger.warn("Error creating configuration with pid: " + pid + " and factory pid: {}", factoryPid,
You can use `Error creating configuration with pid {} and factory pid {}`. No need to mix message formatting with string concatenation

2017-05-10 09:56 UTC, cdealti requested changes

2017-05-10 09:56 UTC, cdealti commented on kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurationServiceImpl.java
> +                                            e);
can you please fix also this?

2017-05-10 13:36 UTC, cdealti approved these changes

2017-05-10 13:37 UTC, merged