[Testing][Refactoring]IfcfgConfigReader/Writer refactoring and tests
eclipse/kura pull request #1425
Opened 2017-06-01 15:08 UTC by markoer

Refactored classes and added unit tests.

Depends on #1402.

@ibinshtok please review

2017-06-06 19:39 UTC, ibinshtok requested changes
@markoer I think scanner needs to be closed, otherwise everything is ok.

2017-06-06 19:39 UTC, ibinshtok commented on kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/visitor/linux/IfcfgConfigReader.java
> -        } finally {
@markoer Do we need to close the scanner?

2017-06-06 20:00 UTC, amitjoy commented on kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/visitor/linux/IfcfgConfigReader.java
> -        } finally {
it's a good practice to close the scanner to avoid resource leak

2017-06-07 08:03 UTC, markoer commented on kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/visitor/linux/IfcfgConfigReader.java
> -        } finally {
`scanner` is declared as a resource in a try-with-resources that automatically closes it at the end of the statement.

2017-06-07 14:52 UTC, ibinshtok approved these changes

2017-06-08 13:48 UTC, merged