Added exists-maven-plugin and maven-enforcer-plugin.
eclipse/kura pull request #1450
Opened 2017-06-13 08:09 UTC by MMaiero

Plugins added both in manifest_pom and target-platform poms.

Signed-off-by: MMaiero <matteo.maiero@eurotech.com>

2017-06-13 08:54 UTC, cdealti requested changes

2017-06-13 08:54 UTC, cdealti commented on kura/manifest_pom.xml
> +        <maven.deploy.skip.prop>false</maven.deploy.skip.prop>
``maven.deploy.skip.prop`` -> ``exists.artifact.already.released``

2017-06-13 08:54 UTC, cdealti commented on kura/manifest_pom.xml
> +            <plugin>
needs build and test dependency CQ (I will open an issue)

2017-06-13 08:54 UTC, cdealti commented on kura/manifest_pom.xml
> +                <groupId>org.apache.maven.plugins</groupId>
CQ build and test dependency needed

2017-06-13 08:54 UTC, cdealti commented on kura/manifest_pom.xml
> +                        <id>enforce-property</id>
``enforce-property`` -> ``fail-on-artifact-already-released``

2017-06-13 08:54 UTC, cdealti commented on kura/manifest_pom.xml
> +                                    <message>Property must be false during execution.</message>
Artifact already exists on the release repository. Forgot to bump version?

2017-06-13 08:54 UTC, cdealti commented on target-platform/pom.xml
> +        <maven.deploy.skip.prop>false</maven.deploy.skip.prop>
same as above

2017-06-13 09:31 UTC, MMaiero commented
Absolutely, the plugins need to be added to the build and test dependency doc before merging the PR. At least we don't miss it.

2017-06-13 11:23 UTC, cdealti commented
Please rebase & update the PR as the build has been fixed by #1441

2017-06-19 08:59 UTC, cdealti commented
@MMaiero failing the build should be avalable out of box with version 0.0.3:

https://github.com/chonton/exists-maven-plugin/issues/1

2017-06-20 12:23 UTC, MMaiero commented
Plugin updated to Version 0.0.3.
The build fails if an artifact already exists remotely

2017-06-28 12:50 UTC, MMaiero commented
Rebased branch.
Created issue for the Build and test dependency.
@pierantoniomerlino I think that if it is ok for you, we can merge.

2017-06-28 13:05 UTC, pierantoniomerlino approved these changes

2017-06-28 13:34 UTC, merged