[Testing][Refactoring] ModemMonitorServiceImpl tests and refactoring
eclipse/kura pull request #1473
Opened 2017-06-23 14:03 UTC by markoer

Added service activation tests. Refactored so that testing was enabled.
Code review/actual test would be appreciated due to changed executor initialization.

@ibinshtok please review.

2017-06-26 18:19 UTC, ibinshtok requested changes
@markoer should we invoke the submitMonitorTask() from the processNetworkConfigurationChangeEvent() method as well?

2017-06-28 12:37 UTC, MMaiero commented on kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImpl.java
> +        this.m_executor = Executors.newSingleThreadExecutor();
If it does not go ever 1k lines, I believe we can also rename the variables according to the new conventions.

2017-07-03 08:27 UTC, markoer commented on kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImpl.java
> +        this.m_executor = Executors.newSingleThreadExecutor();
I need to make updates anyway, so, yes.

2017-07-04 13:15 UTC, MMaiero commented
@ibinshtok Ok for you to merge?

2017-07-05 18:05 UTC, ibinshtok approved these changes

2017-07-05 21:44 UTC, merged

2017-07-06 06:22 UTC, MMaiero commented
@ibinshtok I believe something got broken with your additions: now we have double commits for the same thing by @markoer. Probably you needed to update your branch with upstream before pushing the new commits. Anyway, it should be working anyway.

2017-07-06 14:49 UTC, ibinshtok commented
@MMaiero Yes, it should work. It happened because I forgot to do 'git pull origin' before adding a few more changes and  you have modified the code as well.