TinyB integration and bluetooth APIs refactor
eclipse/kura pull request #1528
Opened 2017-07-14 09:57 UTC by pierantoniomerlino

This PR integrates a new native library for managing BLE devices. Moreover, the bluetooth APIs are refactored both for BLE and beacon. In particular:
- the TinyB lib is added to the target platform using fragments;
- the org.eclipse.kura.bluetooth.le provides a new set of APIs to manage BLE devices;
- the APIs implementation for BLE is in org.eclipse.kura.ble.provider;
- the org.eclipse.kura.bluetooth.le.beacon contains a new APIs for managing a generic beacon advertiser/scanner;
- the org.eclipse.kura.ble.ibeacon.provider implements the APIs for IBeacon devices;
- the org.eclipse.kura.ble.eddystone.provider implements the APIs for Eddystone devices (limited to UID and URL);
- the examples for IBeacon and Eddystone advertiser/scanner are added.

DO NOT MERGE until the CQ for TinyB is approved!

Signed-off-by: pierantoniomerlino <pierantonio.merlino@eurotech.com>

2017-07-18 17:50 UTC, cdealti commented
@pierantoniomerlino the Travis CI build fails

2017-07-25 12:01 UTC, cdealti commented on kura/distrib/src/main/ant/build_equinox_distrib.xml
> +	<target name="tinyb-jars">
isn't there any alternative to this? This ant script is becoming lengthy

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/META-INF/MANIFEST.MF
> + org.eclipse.kura.bluetooth.le;version="1.0.0",
* Fix import version range.
* Should we also change the Bundle-Version? Ask yourself: did I introduce any incompatible change? Did I add new features?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/OSGI-INF/bleExample.xml
> +    <reference bind="setBluetoothLeService"
Good reason to change the Bundle-Version?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +    private static final String APP_ID = "BLE_APP_V2";
Good reason to change the Bundle-Version?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>      private boolean enableScan = false;
**false** intializers not needed

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>              logger.error("Error starting component", e1);
e1 -> e

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +        if (this.bluetoothLeAdapter != null && this.bluetoothLeAdapter.isDiscovering()) {
code duplicated from deactivate. Please refactor

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +            this.cloudClient.publish(topic + "/" + address + "/keys", payload, 0, false);
Some would suggest using an StringBuilder

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +    protected void doPublishKeys(String address, Integer key) {
Integer -> int

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>      private boolean searchSensorTagList(String address) {
a method returning a boolean should start with "is"

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>      private void readProperties(Map<String, Object> properties) {
It would be a good idea to define an Options class for the properties as we did for all the latest projects

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +    private void doScanCallback(List<BluetoothLeDevice> devices) {
* doScanCallback -> onScanCompleted
* Many things are done in this callback. Usually callbacks return quickly deferring the processing.

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +        for (BluetoothLeDevice bluetoothLeDevice : devices) {
Can devices be null?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +            if (bluetoothLeDevice.getName().contains("SensorTag")
Can the device name be null?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>          logger.debug("Found " + this.tiSensorTagList.size() + " SensorTags");
not very useful. Either info or remove

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>                      logger.info("Ambient: " + temperatures[0] + " Target: " + temperatures[1]);
use {} formatting. Please correct other occurrences

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> -                logger.info("Cannot connect to TI SensorTag " + myTiSensorTag.getBluetoothDevice().getAdress() + ".");
at least warn, probably error. Check where error is used

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/.gitignore
> +/bin/
why?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/EddystoneExample.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Copyright header missing

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         <AD id="enableScanning"
don't we usually use properties with names this.is.a.property?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +        <AD id="timeout"
timeout, interval or duration?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         <AD id="topicPrefix"
What part of the semantic topic is this?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +            description="Name of bluetooth adapter."/>
omit period

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +        <AD id="rate_limit"
min period or rate limit?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         <AD id="enableScanning"
I believe our convention is this.is.a.property

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +        <AD id="timeout"
timeout, interval or duration?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         <AD id="topicPrefix"
is this the prefix of the app topic? Can you make an example in the description?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +        <AD id="rate_limit"
rate limit or min publish period?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Copyright header missing

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         description="Eddystone Scanning Example.">
Can you expand the description adding information on Eddystone beacons (or the ones we support)

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +            description="Eddystone scan duration in seconds."/>
Either use periods everywhere or nowhere

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/org.eclipse.kura.example.eddystone.scanner.dpp
> +#Deployment Plugin Project File
this usually goe under src/main/resources. Check other examples

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/pom.xml
> +    Copyright (c) 2011, 2014 Eurotech and/or its affiliates
Fix end date

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/pom.xml
> +	<properties>
needed?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/pom.xml
> +	<build>
needed?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +    private static final char[] HEX_CHAR_ARRAY = "0123456789ABCDEF".toCharArray();
See comment above. Please implement an Options class for the properties

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +    private String adapterName;
Rename accordingly

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +package org.eclipse.kura.example.eddystone.scanner;
Copyright header missing

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +        // See http://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing/20434019#20434019
remove code copied from Stackoverflow (if any)

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +                    kp.addMetric("Namespace", bytesArrayToHexString(eddystone.getNamespace()));
metric names are usually lowercase

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/EddystoneExample.xml
> +    Contributors:
Remove contributors

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.EddystoneExample.xml
> +    Copyright (c) 2011, 2016 Eurotech and/or its affiliates
Fixe end date

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.EddystoneExample.xml
> +    Contributors:
remove contributors

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.EddystoneExample.xml
> +         name="Eddystone Example"
This is an Eddystone advertiser. Rename consistently

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.EddystoneExample.xml
> +         description="Simple Eddystone example.">
Same as for the scanner. What is it advertised?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.EddystoneExample.xml
> +         <AD id="enableAdvertising"
Same as for the scanner

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/org.eclipse.kura.example.eddystone.dpp
> +#Deployment Plugin Project File
Same as for the advertiser

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/pom.xml
> +    Copyright (c) 2011, 2016 Eurotech and/or its affiliates
Fix end date

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/pom.xml
> +    Contributors:
Remove contributors

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/pom.xml
> +	<properties>
Needed?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/pom.xml
> +	<build>
Needed?

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/src/main/java/org/eclipse/kura/example/eddystone/EddystoneExample.java
> + * Copyright (c) 2011, 2016 Eurotech and/or its affiliates
Fix end date

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/src/main/java/org/eclipse/kura/example/eddystone/EddystoneExample.java
> + * Contributors:
Remove contributors

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/src/main/java/org/eclipse/kura/example/eddystone/EddystoneExample.java
> +    private static final String PROPERTY_ENABLE = "enableAdvertising";
options

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.eddystone/src/main/java/org/eclipse/kura/example/eddystone/EddystoneExample.java
> +    private void readProperties(Map<String, Object> properties) {
options

2017-07-25 12:01 UTC, cdealti commented on kura/examples/org.eclipse.kura.example.ibeacon.scanner/.gitignore
> +/bin/
For each remaining example: same considerations above

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
> + org.eclipse.kura.clock;version="1.0.1",
why?

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraBluetoothCommandException.java
> +package org.eclipse.kura;
Copyright header missing. Please double check every file in this PR has the correct copyright header

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeAdapter.java
> +    // This is the class of the bluetooth device.
???

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeAdapter.java
> + * Contributors:
Remove contributors here and in the following

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeAdapter.java
> +    public void stopDiscovery() throws KuraException;
You have defined many new bluetooth exceptions to throw a generic KuraException?
I expect that most of these methods may throw exceptions.

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeAdapter.java
> +    public Future<BluetoothLeDevice> findDeviceByAddress(long timeout, String address);
not sure we should support both the Future and Consumer API. The latter allows an application to wait on its own Future if so it desires. I propose to remove the it.

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeDevice.java
> +    public BluetoothLeGattService findService(UUID uuid) throws KuraException;
See above point on exceptions

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeDevice.java
> +     *            The UUID of the GATT service
formatting needed?

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeDevice.java
> +     */
formatting

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeDevice.java
> +    // This is the class of the bluetooth device.
fix these comments

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeGattCharacteristicProperties.java
> +        int prop = 0x00;
define an UNKNOWN code

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeGattCharacteristicProperties.java
> +    public static int getCode(String property) {
do you really need this? One can use the getProperty().getValue()

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeGattCharacteristicProperties.java
> +public enum BluetoothLeGattCharacteristicProperties {
* Javadoc
* noextend
* ProviderType

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeGattCharacteristicProperties.java
> +    public static BluetoothLeGattCharacteristicProperties getProperty(String property) {
getProperty -> valueOf

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportRecord.java
> +    private int eventType;
Do we need enums for event and address types

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +    private byte packetType;
do we need enums for packet type and sub event code?

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +    public static final byte AD_BYTES_NUMBER = 02;
* why an octal constant?
* why do you need to expose them? Maybe they are only relevant for the concrete implementation?

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +    public BluetoothLeBeacon() {
Why do you need to set these defaults?

2017-07-25 12:01 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +public abstract class BluetoothLeBeacon {
* Do we really need this abstract class in API? What about an interface?
* noextend
* ProviderType

2017-07-25 12:02 UTC, cdealti commented
@pierantoniomerlino I haven't finished the review but you can start fixing the most trivial stuff

2017-07-25 12:47 UTC, pierantoniomerlino commented on kura/distrib/src/main/ant/build_equinox_distrib.xml
> +	<target name="tinyb-jars">
I confess that I don't like this solution, but I didn't find a better one. However, if we can live with the libs for all the architectures in to the plugin folder, we can remove it.

2017-07-25 13:43 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/META-INF/MANIFEST.MF
> + org.eclipse.kura.bluetooth.le;version="1.0.0",
The previous BLE example was released with version 1.0.100. Since I did some modifications on this bundle I increased the version to 1.0.200.

2017-07-25 13:44 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>      private boolean enableScan = false;
👍

2017-07-25 13:46 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +        if (this.bluetoothLeAdapter != null && this.bluetoothLeAdapter.isDiscovering()) {
I'll extract a method...

2017-07-25 13:53 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +            this.cloudClient.publish(topic + "/" + address + "/keys", payload, 0, false);
I had the same doubt, so I did some research and I found [this](https://stackoverflow.com/questions/1532461/stringbuilder-vs-string-concatenation-in-tostring-in-java).

2017-07-25 13:54 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +            this.cloudClient.publish(topic + "/" + address + "/keys", payload, 0, false);
At the end, I decided not to use the StringBuilder.

2017-07-25 13:56 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>      private boolean searchSensorTagList(String address) {
Replaced with ``ìsSensorTagInList```.

2017-07-25 16:08 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>      private void readProperties(Map<String, Object> properties) {
👍

2017-07-26 09:52 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>          logger.debug("Found " + this.tiSensorTagList.size() + " SensorTags");
Useful during debugging :-) I'm going to remove it.

2017-07-26 12:59 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +    private void doScanCallback(List<BluetoothLeDevice> devices) {
I removed the callback and I replaced it with the synchronous scan method. Moreover, I tried to split the huge method that reads the SensorTags in multiple little ones.

2017-07-26 13:01 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +        for (BluetoothLeDevice bluetoothLeDevice : devices) {
No, at least an empty list.

2017-07-26 13:02 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> +            if (bluetoothLeDevice.getName().contains("SensorTag")
No

2017-07-26 13:08 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
>                      logger.info("Ambient: " + temperatures[0] + " Target: " + temperatures[1]);
👍

2017-07-26 13:09 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.ble.tisensortag/src/main/java/org/eclipse/kura/example/ble/tisensortag/BluetoothLe.java
> -                logger.info("Cannot connect to TI SensorTag " + myTiSensorTag.getBluetoothDevice().getAdress() + ".");
Changed to warning.

2017-07-26 13:25 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/.gitignore
> +/bin/
I didn't noticed that file. IMHO it is not needed for this example and also for iBeacon scanner. I'll delete them.

2017-07-26 13:29 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/.gitignore
> +/bin/
Moreover, there are several copies of this file in our examples. Probably they should be deleted as well.

2017-07-26 13:47 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Added all missing copyright headers.

2017-07-26 13:59 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         description="Eddystone Scanning Example.">
"Enable scan for Eddystones. Only UID and URL frame types are supported."
Or should I add more details on Eddystones?

2017-07-26 14:01 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         <AD id="enableScanning"
We use different conventions on the parameter names. Probably we should chose one and modify accordingly all the bundles. Should I use this.is.a.property convention?

2017-07-26 14:25 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.scanner.EddystoneScannerExample.xml
> +         <AD id="enableScanning"
Ok, I'll use it.

2017-07-26 14:46 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/org.eclipse.kura.example.eddystone.scanner.dpp
> +#Deployment Plugin Project File
👍

2017-07-26 15:37 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +    private static final char[] HEX_CHAR_ARRAY = "0123456789ABCDEF".toCharArray();
I agree with you about Options class if there is a lot of parameters (like Sensortag example), but here we have only 5.

2017-07-26 15:40 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone.scanner/src/main/java/org/eclipse/kura/example/eddystone/scanner/EddystoneScannerExample.java
> +        // See http://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing/20434019#20434019
No, it's only for reference. However, I removed the comment because is not relevant.

2017-07-27 09:13 UTC, pierantoniomerlino commented on kura/examples/org.eclipse.kura.example.eddystone/OSGI-INF/metatype/org.eclipse.kura.example.eddystone.EddystoneExample.xml
> +         name="Eddystone Example"
We could rename our examples in this way:
IBeaconExample -> IBeaconAdvertiser
IBeaconScannerExample -> IBeaconScanner
EddystoneExample -> EddystoneAdvertiser
EddystoneScannerExample -> EddystoneScanner

2017-07-27 10:15 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
> + org.eclipse.kura.clock;version="1.0.1",
If you refer to the clock package, it was moved during a rebase.

2017-07-27 10:36 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeAdapter.java
> +    public Future<BluetoothLeDevice> findDeviceByAddress(long timeout, String address);
We can think about this. IMHO, it is better to offer more flexibility to the user. But this can be more complex and less user-friendly.

2017-07-27 11:47 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeAdapter.java
> +    public void stopDiscovery() throws KuraException;
Most of the methods simply call the tinyb methods and these don't throw any exception. I'll modify the exceptions thrown in the remaining cases.

2017-07-27 13:47 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/BluetoothLeDevice.java
> +     *            The UUID of the GATT service
The formatter does it automatically!

2017-07-27 15:30 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportRecord.java
> +    private int eventType;
I don't know if this is really useful or not.

2017-07-27 15:31 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +    private byte packetType;
As AdvertisingReportRecord, I don't know if this can be useful or not.

2017-07-28 09:31 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportRecord.java
> +    private int eventType;
Ok, I added enums for the event and address types.

2017-07-28 09:32 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +    private byte packetType;
In this case, there are a lot of packet and event codes and most of them aren't very useful for our applications. I prefer to leave the code unchanged for now.

2017-07-28 09:59 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +public abstract class BluetoothLeBeacon {
We have fields that are common to all beacons, so I prefer to keep them here using an abstract class.

2017-07-28 10:02 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +    public static final byte AD_BYTES_NUMBER = 02;
The octal is an error. Also these constants are common to all beacons.

2017-07-28 10:03 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +    public BluetoothLeBeacon() {
Yes, because these are the common configuration for a beacon.

2017-07-31 11:57 UTC, cdealti requested changes

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportAddressType.java
> +    public static AdvertisingReportAddressType getAddressType(byte address) {
getAddressType -> valueOf

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportAddressType.java
> +        AdvertisingReportAddressType type = null;
to be consistent with other comments in this review, instead of returning null, wouldn't be better to return a special UNKNOWN value or throw an exception?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportAddressType.java
> +package org.eclipse.kura.bluetooth.le.beacon;
Copyright headers

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportAddressType.java
> +    PUBLIC((byte) 0x00), // Public Device Address
Use javadoc comments to document the constants

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportEventType.java
> +package org.eclipse.kura.bluetooth.le.beacon;
See all above comments

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportRecord.java
> +        // Not used
why this comment? Can't you just omit the contructor?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +    private byte packetType;
>  I prefer to leave the code unchanged for now

> It's either now or never.

The Bluetooth 4.0 specification show:
- 4 types of Packet Type
- almost 70 types of Event Codes for HCI Event Packet type (0x04)
- 5 type of Sub-Event Codes for LE MetaEvent event type (0x3e)

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +        this.rawData = new byte[rawData.length];
why do we need to copy the array?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +        if (this.reportRecords == null) {
why this lazy initialization?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeacon.java
> +    public static final byte AD_BYTES_NUMBER = 0x02;
What are these constants for?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconAdvertiser.java
> +    public void startBeaconAdvertising() throws KuraException;
* Can this be called before calling update methods below? Will you get an exception?
* Javadoc does not document the exception
* KuraException is too generic

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconAdvertiser.java
> +    public void updateBeaconAdvertisingInterval(Integer min, Integer max) throws KuraException;
* Integer -> long (as long is usually used for time)
* What are the time units?
* I believe there will be some validation that min <= max and a suitable exception is thrown

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconAdvertiser.java
> +     *
shall we describe whether updating a beacon affects the beacon interval?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconCodec.java
> + * BluetoothLeBeaconFactory allows to create a list of specific BluetoothLeBeacon objects from a
Please rewrite the Javadoc.
Generally speaking what the difference between an "beacon" and an "advertisement". Why do we need both terms?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconCodec.java
> +    public T decode(byte[] reportData);
* Javadoc
* reportData?

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconCodec.java
> +    public byte[] encode(T beacon);
Javadoc

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconListener.java
> +package org.eclipse.kura.bluetooth.le.beacon;
ConsumerType types should live in a separate package e.g.  org.eclipse.kura.bluetooth.le.beacon.listener

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconScanner.java
> +    public void startBeaconScan(long timeout) throws KuraException;
* Javadoc missing
* KuraException is too generic

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/package-info.java
> + * @author pierantonio.merlino
remove author.

I believe package-info is missing in other packages

2017-07-31 11:57 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothLeBeaconService.java
> + * BluetoothLeBeaconService provides a mechanism for interfacing with specific Bluetooth LE Beacon devices.
There something wrong with this service.
It's weird that an application has to know about `BluetoothLeBeaconCodec<T>` (which the application does not use) when it only needs `BluetoothLeBeaconScanner<T>` and `T`.
It should be probably something like:

```
public interface BluetoothLeBeaconService T extends BluetoothLeBeacon {
    public BluetoothLeBeaconScanner<T> getBeaconScanner(BluetoothLeAdapter adapter);
...
}
```

2017-07-31 13:06 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +    private byte packetType;
Never.

2017-07-31 13:12 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportAddressType.java
> +        AdvertisingReportAddressType type = null;
We return RESERVED.

2017-07-31 13:31 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/AdvertisingReportRecord.java
> +        // Not used
Removed.

2017-07-31 15:42 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +        this.rawData = new byte[rawData.length];
No, I deleted it.

2017-07-31 15:42 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/le/beacon/BluetoothAdvertisementData.java
> +        if (this.reportRecords == null) {
Because of the lack of a constructor. I added it.

2017-09-07 09:06 UTC, merged