Enh platform segregation
eclipse/kura pull request #2172
Opened 2018-08-02 11:42 UTC by MMaiero

2018-08-06 12:31 UTC, cdealti requested changes

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/NetConfigManager.java
> +/*******************************************************************************
I believe we should define a provisional (`x-internal`) API [1] in the bundle`org.eclipse.kura.linux.net`.

As this service interface serializes and deserializes a NetInterfaceConfig to the OS network configuration files (Debian `ifupdown`, Fedora `network-scripts` etc), a better name could be NetInterfaceConfigSerializationService. Add Javadoc explaining the purpose of this service.

[1] http://www.vogella.com/tutorials/OSGi/article.html

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/NetConfigManager.java
> +    public void readConfig(NetInterfaceConfig<? extends NetInterfaceAddressConfig> netConfig,
Add Javadoc explaining what NetInterfaceConfig fields the caller should set before the configuration can be read (probably only the interface name is needed and not modified).

I don't understand the meaning of the second kuraExtendedProps parameter.

I believe that read and write should be enough as method names.

Finally, throwing a generic KuraException is not a good practice unless we document all the possible error codes: the configuration may not be valid, then some IOException may occur...

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +/*******************************************************************************
Please see above about creating a provisional API.

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +public interface DnsServer {
maybe rename to `DnsServerService`.

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +    public boolean isEnabled();
`isRunning`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +    public void enable() throws KuraException;
`start`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +    public void disable() throws KuraException;
`stop`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +    public void setConfig(DnsServerConfig dnsServerConfig) throws KuraException;
`writeConfiguration`. It will likely throw `IOException`s (avoid throwing generic `KuraException`s).

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +    public DnsServerConfig getDnsServerConfig();
`readConfiguration`. It will likely throw `IOException`s

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dns/DnsServer.java
> +    public String getConfigFilename();
Do we really need to expose this detail?

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/modem/GatewayModemDriver.java
> +package org.eclipse.kura.net.modem;
Please see above about creating a provisional API.

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/modem/GatewayModemDriver.java
> +    public void turnModemOff(String vendor, String product) throws KuraException;
The USB vendor and product identifiers do not uniquely identify a modem as more than one modem with the same VID&PID may exist in the system. The path of the USB device would be a better option.

More generally, a service interface to control the power state of a "device" would help (see for example `WifiUtils` below):
```
interface BoardPowerService {
   void turnOn(BoardPowerDomain domain, String identifier) throws UnsupportedOperationException, IOException...
   void turnOff...
   void reset...
   BoardPowerState getState...
}
```
Where `BoardPowerDomain` can be for example `USB_DEVICE`, `NETWORK_INTERFACE` etc. and prevents clashes between identifiers belonging to different domains:
```
turnOn(BoardPowerDomain.USB_DEVICE, "1-1.2")
turnOn(BoardPowerDomain.NETWORK_INTERFACE, "wlan1")
```

BoardPowerState represents the following constants: `ON, OFF, TURNING_ON, TURNING_OFF, RESETTING`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/wifi/WifiUtils.java
> +package org.eclipse.kura.net.wifi;
Please see above about creating a provisional API.

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/wifi/WifiUtils.java
> +public interface WifiUtils {
Based on the above comment, this service interface (an utility is generally implemented as a class with only static methods), would only manage loading the right kernel module for a mode. This is sometimes needed for WiFi interfaces where switching between access point and station mode requires loading a specific firmware. Maybe rename to `WifiDriverService`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/wifi/WifiUtils.java
> +    public boolean isWifiDeviceOn(String interfaceName);
Remove based on the comments to `GatewayModemDriver`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/wifi/WifiUtils.java
> +    public void turnWifiDeviceOn(String interfaceName) throws KuraException;
Remove based on the comments to `GatewayModemDriver`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/wifi/WifiUtils.java
> +    public void turnWifiDeviceOff(String interfaceName) throws KuraException;
Remove based on the comments to `GatewayModemDriver`

2018-08-06 12:31 UTC, cdealti commented on kura/org.eclipse.kura.linux.debian.provider/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
The bundle name should probably be `org.eclipse.kura.linux.net.debian.provider`. It should work with all Debian derivatives that use `ifupdown` to configure the networking

2018-08-27 13:49 UTC, MMaiero commented on kura/org.eclipse.kura.linux.debian.provider/META-INF/MANIFEST.MF
> + org.eclipse.kura.core.net;version="1.0.5",
TODO: review import

2018-08-27 13:50 UTC, MMaiero commented on kura/org.eclipse.kura.linux.debian.provider/build.properties
> +# Copyright (c) 2011, 2016 Eurotech and/or its affiliates
2018

2018-08-27 14:06 UTC, MMaiero commented on kura/org.eclipse.kura.linux.redhat.provider/build.properties
> +# Copyright (c) 2011, 2016 Eurotech and/or its affiliates
2018

2018-08-27 14:07 UTC, MMaiero commented on kura/org.eclipse.kura.linux.systemd.provider/build.properties
> +# Copyright (c) 2011, 2016 Eurotech and/or its affiliates
2018

2018-08-27 14:09 UTC, MMaiero commented on kura/org.eclipse.kura.linux.sysv.provider/build.properties
> +# Copyright (c) 2011, 2016 Eurotech and/or its affiliates
2018

2018-08-27 14:13 UTC, MMaiero commented on kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/he910/TelitHe910.java
> +    /**
Delete

2018-08-30 13:03 UTC, nicolatimeus approved these changes

2018-08-30 13:04 UTC, merged