Fixed missed command service activation when run in development env.
eclipse/kura pull request #2444
Opened 2019-05-15 11:47 UTC by MMaiero

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

2019-05-16 15:05 UTC, markoer requested changes

2019-05-16 15:05 UTC, markoer commented on kura/org.eclipse.kura.core.cloud/OSGI-INF/commandCloudApp.xml
> +<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" activate="activate" configuration-policy="require" deactivate="deactivate" enabled="true" immediate="true" modified="updated" name="org
(c) year 2018 -> 2019

2019-05-21 09:13 UTC, MMaiero commented on kura/org.eclipse.kura.core.cloud/OSGI-INF/commandCloudApp.xml
> +<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" activate="activate" configuration-policy="require" deactivate="deactivate" enabled="true" immediate="true" modified="updated" name="org
done

2019-05-28 11:34 UTC, MMaiero commented
@markoer Can this be merged?

2019-05-28 11:52 UTC, markoer approved these changes

2019-05-28 14:27 UTC, merged