Drag-and-drop of dp files
eclipse/kura pull request #2959
Opened 2020-06-22 15:45 UTC by pierantoniomerlino

This PR adds the possibility to drag-and-drop deployment packages directly from the local filesystem.

**Related Issue:** This PR fixes/closes #2940 

Thanks to @nicolatimeus for the contribution!

2020-06-23 10:24 UTC, LeoNerdoG requested changes
Hey @pierantoniomerlino,
I have checked this PR and I have two comments:
1. please fix the header in DropSupport.java file
2. if user selects multiple packages from desktop and drops them in kura, Kura asks user if he wants to install the package (only one package) - if you say yes, nothing happens. Is this something we can ignore or should be fixed. 
All other scenarios are OK.

2020-06-23 10:24 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/util/DropSupport.java
> +import java.util.List;
Please update header of the file.

2020-06-23 11:57 UTC, MMaiero commented
I believe it works great!
I have tested the corner case with multiple dps selected. In my case it actually installed one of them.
But yes, we should take care of that case, in order to prevent issues. Can we check the number of files selected? If so, we may want to throw an error due to the fact that we support just one dp at a time.

2020-06-23 11:59 UTC, MMaiero commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/packages/PackagesPanelUi.java
> +
maybe, for readability, it is better to move the content to a specific method.

2020-06-24 07:35 UTC, MMaiero approved these changes
I made a small change in the message when multiple dp files are provided. @pierantoniomerlino can you have a look at it? Other than that for me it can be merged.

2020-06-24 07:36 UTC, pierantoniomerlino commented
@MMaiero For me is ok!

2020-06-24 08:27 UTC, merged