Modified modal config in firewall to prevent closing.
eclipse/kura pull request #2965
Opened 2020-07-01 14:22 UTC by MMaiero

If the user clicks outside the modal.

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2963

2020-07-02 06:54 UTC, LeoNerdoG commented
Hey @MMaiero,
I have checked this and is solves the issue in the Firewall service. 
May I suggest to fix this in all other service also? I think the best way is to fix all of these same issues in one PR. 
What do you think?

2020-07-02 06:59 UTC, MMaiero commented
Do we have a list of the modals that should be tuned that way?

2020-07-02 07:28 UTC, LeoNerdoG commented
I will make a list and post it here.

2020-07-15 07:49 UTC, LeoNerdoG commented
Hey @MMaiero,
bellow you will find the list of modals. 

 - New button in Firewall -> Open Ports
 - Edit button in Firewall -> Open Ports
 - New button in Firewall -> Port Forwarding
 - Edit button in Firewall -> Port Forwarding
 - New button in Firewall -> IP Forwarding/Masquerading
 - Edit button in Firewall ->  IP Forwarding/Masquerading
 - New Connection button in Cloud Connections
 - New Pub/Sub button in Cloud Connection
 - New Driver button in Drivers and Assets
 - New Asset button in Drivers and Assets
 - Upload Channels button in Drivers and Assets -> Asset 
 - WireAsset asset in Wire graph
 - Install/Upgrade button in packages
 - Upload and Apply button in Settings -> Snapshot

2020-07-16 08:23 UTC, MMaiero commented
Made few changes that should cover (hopefully) most of the modals reported to be updated

2020-07-16 08:24 UTC, LeoNerdoG commented
OK I will check.

2020-07-21 06:07 UTC, LeoNerdoG commented
hey @MMaiero, 
I have checked this PR and everything looks fine except the  "WireAsset asset in Wire graph" - this one can stille be closed with clikc outside the new window. Is this deliberate? Can you please check?

2020-07-22 07:05 UTC, LeoNerdoG requested changes
hey @MMaiero can you please update some headers?

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/AlertDialog.ui.xml
> +    <b:Modal closable="false" fade="true" dataBackdrop="STATIC"
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/ServicesUi.java
> +import org.gwtbootstrap3.client.ui.constants.ModalBackdrop;
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudConnectionsUi.java
> +import org.gwtbootstrap3.client.ui.constants.ModalBackdrop;
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudInstancesUi.java
> +        alertDialog.show(MSGS.cloudServiceDeleteConfirmation(), () -> {
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudInstancesUi.ui.xml
> +            <b:Modal closable="false" fade="true" dataBackdrop="STATIC"
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.ui.xml
> +            <b:Modal closable="false" fade="true" dataBackdrop="STATIC" dataKeyboard="true" b:id="new-channel-modal"
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/DriversAndAssetsUi.ui.xml
> +            <b:Modal closable="false" fade="true" dataBackdrop="STATIC"
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/NetworkInterfacesTableUi.java
> +import org.gwtbootstrap3.client.ui.constants.ModalBackdrop;
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/CommandUserTabUi.java
> +import org.gwtbootstrap3.client.ui.constants.ModalBackdrop;
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SnapshotsTabUi.ui.xml
> +            <b:Modal closable="false" fade="true" dataBackdrop="STATIC"
Please update header to "2020".

2020-07-22 07:05 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SslTabUi.java
> +import org.gwtbootstrap3.client.ui.constants.ModalBackdrop;
Please update header to "2020".

2020-07-22 11:54 UTC, MMaiero commented
Done

2020-07-27 12:07 UTC, LeoNerdoG approved these changes

2020-07-27 12:07 UTC, LeoNerdoG commented
Hey @MMaiero,
I ahve checked this PR and it looks OK. I think it can be merged in develop.

2020-07-27 12:08 UTC, merged