Removed icons in confirmation buttons to match the other elements in UI
eclipse/kura pull request #2974
Opened 2020-07-03 15:12 UTC by MMaiero

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

Closes #2699

2020-07-06 12:04 UTC, LeoNerdoG requested changes
Hey @MMaiero,
I have checked this PR and it looks OK - after updating the headers this can be merged into develop.

2020-07-06 12:04 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.ui.xml
> +                    <b:Button b:id="btn-create-channel-cancel" type="PRIMARY" dataDismiss="MODAL"
Please update the year in th header to 2020.

2020-07-06 12:04 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/wires/WiresDialogs.ui.xml
> +                <b:Button b:id="btn-create-comp-cancel" type="PRIMARY" dataDismiss="MODAL"
Please update the year in th header to 2020.

2020-07-06 13:43 UTC, MMaiero commented
Done

2020-07-07 06:05 UTC, LeoNerdoG approved these changes

2020-07-07 06:44 UTC, merged