Fix connection delete enabled
eclipse/kura pull request #2976
Opened 2020-07-06 06:52 UTC by MMaiero

Closes #2686

2020-07-07 06:26 UTC, LeoNerdoG commented
Hey @MMaiero
I have checked this and have one comment - if user deselects a certain cloud connection,  the buttons are properly disabled, but the bottom window with all the parameters is still visible:
![Screenshot 2020-07-07 at 08 25 02](https://user-images.githubusercontent.com/15121999/86727166-78bcfe80-c02b-11ea-9994-84d61b59ce0a.png)

Can you hide the bottom window when nothing is selected? I think this can be done in this PR, if you agree?

2020-07-07 07:27 UTC, MMaiero commented
How do you get to the condition where no lines are selected? I cannot get to that point...

2020-07-08 11:00 UTC, LeoNerdoG commented
Hey @MMaiero,
according to the codu you wrote the behaviour is that if user tries to deselct a cloud connection, first one is selected. 
Is this the behaviour you wanted? Because it is how it's manifested in the UI.

2020-07-08 11:01 UTC, MMaiero commented
yes, matches what we talked yesterday

2020-07-08 11:02 UTC, LeoNerdoG commented
Ok then this can be merged! 😄

2020-07-08 11:12 UTC, LeoNerdoG requested changes
Please update the header in one of the files.

2020-07-08 11:12 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudInstancesUi.java
> +        GwtCloudEntry selectedCloudEntry = this.selectionModel.getSelectedObject();
Please update header to 2020.

2020-07-08 14:55 UTC, MMaiero commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudInstancesUi.java
> +        GwtCloudEntry selectedCloudEntry = this.selectionModel.getSelectedObject();
Done

2020-07-15 15:34 UTC, merged