Added confirmation window when switching between tabs in Settings section
eclipse/kura pull request #2978
Opened 2020-07-07 13:44 UTC by pierantoniomerlino

This PR modifies the behavior of the Settings section, adding messages for alerting the user that he'll lose the filled data when switch to another tab.

**Related Issue:** This PR fixes/closes #2717

2020-07-07 14:50 UTC, MMaiero commented
I believe Pierantonio and I are working on the same things: see #2972. Probably due to duplicate issues? Or I am wrong?

2020-07-07 14:55 UTC, pierantoniomerlino commented
@MMaiero The issues were partially tracked in #2717 where we agreed on adding some warning messages for the user when he changes tab. So, yes, it's a (partial) duplicate issue...

2020-07-08 06:38 UTC, MMaiero commented
I believe we can then close my PR and use this as it seems more complete

2020-07-08 06:38 UTC, MMaiero approved these changes

2020-07-08 11:29 UTC, LeoNerdoG requested changes
Hey @pierantoniomerlino,
I have checked this PR. Code-wise please fix the headers. 
UI-wise: i found an issue (it happens on all of the tabs in Settings).

I think the easiest way will be through a Testflow:
1. Go to Settings tab, select one of "SSL" tabs
2. Enter something in on of the fields
3. Without applying changes click on another tab in Settings
4. When prompted to discarc changes select "No"
5. Again click on another tab and when prompted for discarding changes click "Yes"
6. Return to the previous tab and observe Apply and Reset buttons - they are both enabled! 

Can you please check on your side and confirm the issue?

2020-07-08 11:29 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/AbstractServicesUi.java
> +    public abstract void setDirty(boolean flag);
Please change header to "2020".

2020-07-08 11:29 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/ConfigurableComponentUi.java
> +    public void reset() {
Please change header to "2020".

2020-07-08 11:29 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.java
> +    public void reset() {
Please change header to "2020".

2020-07-08 11:29 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/CommandUserTabUi.java
> +import org.eclipse.kura.web.client.ui.Tab;
Please change header to "2020".

2020-07-08 11:29 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SettingsPanelUi.java
> +import org.eclipse.kura.web.client.ui.Tab.RefreshHandler;
Please change header to "2020".

2020-07-08 11:29 UTC, LeoNerdoG commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SslTabUi.java
> +import org.eclipse.kura.web.client.ui.Tab;
Please change header to "2020".

2020-07-08 12:23 UTC, pierantoniomerlino commented
@LeoNerdoG Yes, I confirm the issue

2020-07-08 14:04 UTC, pierantoniomerlino commented
@LeoNerdoG now the issues should be fixed.

2020-07-10 07:56 UTC, LeoNerdoG commented
Hey @pierantoniomerlino,
I have checked this and now there is no prompt for discarding changes if user clicks another tab without applying changes on current tab. The changes are automatically discarded - can you please check?

2020-07-10 09:20 UTC, merged