Fixes case where a read for all channels fails and reports empty value.
eclipse/kura pull request #3042
Opened 2020-08-21 13:50 UTC by MMaiero

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

2020-08-24 09:34 UTC, nicolatimeus approved these changes

2020-08-24 11:39 UTC, MMaiero commented
Closes #3044

2020-08-24 11:40 UTC, MMaiero commented
@mstankovic Can you please validate this PR?

2020-08-25 06:16 UTC, LeoNerdoG requested changes
hey @MMaiero, please update the header in one of the files.

2020-08-25 06:16 UTC, LeoNerdoG commented on kura/org.eclipse.kura.asset.cloudlet.provider/src/main/java/org/eclipse/kura/internal/asset/cloudlet/AssetCloudlet.java
> +import java.util.stream.Collectors;
Please change header to "2020".

2020-08-25 07:06 UTC, MMaiero commented on kura/org.eclipse.kura.asset.cloudlet.provider/src/main/java/org/eclipse/kura/internal/asset/cloudlet/AssetCloudlet.java
> +import java.util.stream.Collectors;
Done

2020-08-25 07:44 UTC, LeoNerdoG approved these changes

2020-08-25 08:36 UTC, merged