Added support for password change on login
eclipse/kura pull request #3760
Opened 2022-01-26 15:01 UTC by nicolatimeus

**Description of the solution adopted:** 

Allows the admin to enforce password change for an identity at next login:
* A new dialog for password change will be shown after login if password change is requested
* Web ui access, most GWT RPCs and REST APIs will return unauthorized status until the password is changed
* Certificate based access is still permitted

2022-01-26 16:06 UTC, MMaiero commented
@marcellorinaldo Can you please have a review of this PR? Thanks.

2022-01-27 15:40 UTC, marcellorinaldo requested changes

2022-01-27 15:40 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/UserManager.java
> +        return "true".equals(asUser.getProperties().get("kura.need.password.change"));
I would use the constant KURA_NEED_PASSWORD_CHANGE here instead of the hard-coded value

2022-01-27 15:40 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/GwtUserConfig.java
>      public boolean isPasswordAuthEnabled() {
I would also add a constant PASSWORD_ENABLED_KEY for string "password.enabled"

2022-01-27 15:47 UTC, marcellorinaldo commented
If minimum password length is 0 (disabled) and digits, special chars, and uppercase and lowercase letters are required, then the password change on next login is not validating such restrictions. Only the first one seems to be validated (at least one digit).

2022-01-28 09:13 UTC, MMaiero commented
Just to double check, can also the admin user forced to change its password during the first login?

2022-01-28 09:48 UTC, nicolatimeus commented
Yes, the feature works the same regardless of assigned permissions

2022-01-28 09:49 UTC, MMaiero commented
Great! Thanks!

2022-02-03 10:41 UTC, MMaiero commented
I have updated snapshots 0 to require password change by default.
If the change is ok, we can definitely merge

2022-02-03 10:41 UTC, MMaiero approved these changes

2022-02-03 11:22 UTC, marcellorinaldo approved these changes

2022-02-03 11:54 UTC, merged