Unlock radio mode and channel selection in WiFi station mode
eclipse/kura pull request #3859
Opened 2022-03-10 16:56 UTC by salvatore-coppola

Now radio mode is unlocked in WiFi station mode.
Now in station mode it is possible to select the channel to use from the bottom drop-down menu.
If the network search function is used, the suggested channel will be checked against the current device regdom.

2022-03-11 10:18 UTC, marcellorinaldo requested changes

2022-03-11 10:18 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.java
> +    Modal regDomModal;
I would name this regDomErrorModal to make it clear that it pops out only on error

2022-03-11 10:54 UTC, marcellorinaldo commented
Tested successfully on RaspberryPi4.

2022-03-14 09:04 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.java
> +    private int geChannelIndexFromValue(int channelValue) {
Please fix typo.

2022-03-14 10:20 UTC, marcellorinaldo approved these changes

2022-03-14 10:42 UTC, marcellorinaldo approved these changes

2022-03-14 11:23 UTC, marcellorinaldo approved these changes

2022-03-14 13:30 UTC, pierantoniomerlino approved these changes

2022-03-15 08:55 UTC, merged