feat: Add container entrypoint override support to container orchestrator
eclipse/kura pull request #3973
Opened 2022-05-04 15:04 UTC by GregoryIvo

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to inderstand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2022-05-09 04:15 UTC, GregoryIvo commented
@marcellorinaldo This PR should be ready to go. Kindly review it at your earliest convenience. Cheers!

2022-05-09 08:09 UTC, marcellorinaldo requested changes
Tested working correctly on raspberry pi 4.

2022-05-09 08:09 UTC, marcellorinaldo commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/container/orchestration/ContainerConfiguration.java
> +     * the default container entrypoint will be used.
I wouldn't explain in the javadocs what the code will do. Maybe just say that an empty list can be returned if no entry points are specified

2022-05-09 08:09 UTC, marcellorinaldo commented on kura/org.eclipse.kura.container.provider/src/main/java/org/eclipse/kura/container/provider/ContainerInstanceOptions.java
> +            stringList.add(entry.trim());
I would add a check before adding to `stringList`:
`entry.trim().length() > 0`
To prevents having lists like `[,,xyz]`

2022-05-09 08:09 UTC, marcellorinaldo commented on kura/test/org.eclipse.kura.container.provider.test/src/test/java/org/eclipse/kura/container/provider/ContainerInstanceOptionsTest.java
> +        this.properties.put(CONTAINER_ENTRY_POINT, DEFAULT_CONTAINER_ENTRY_POINT);
I would add some `then*` condition to check for the new property.

2022-05-09 15:21 UTC, GregoryIvo commented
@marcellorinaldo  I made your suggested changes, kindly re-review at your earliest convenience. :)

2022-05-09 15:21 UTC, marcellorinaldo approved these changes

2022-05-10 06:52 UTC, marcellorinaldo approved these changes

2022-05-10 15:26 UTC, merged