feat: Added support for timestamp in log entry
eclipse/kura pull request #4042
Opened 2022-07-07 10:18 UTC by MMaiero

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

2022-07-08 07:49 UTC, marcellorinaldo requested changes
In https://github.com/eclipse/kura/blob/14773ce93f3a724fc4a203ecbb1ede8883dc740f/kura/org.eclipse.kura.log.filesystem.provider/src/main/java/org/eclipse/kura/log/filesystem/provider/KuraLogLineParser.java#L116 we could set the timestamp in the constructor of `LogEntry`.

In the web UI, we could also use `LogEntry.getTimestamp` in the creation of the `GwtLogEntry` https://github.com/eclipse/kura/blob/14773ce93f3a724fc4a203ecbb1ede8883dc740f/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtLogServiceImpl.java#L72

Such class will need some modifications like using the passed timestamp for creating the "pretty" message https://github.com/eclipse/kura/blob/14773ce93f3a724fc4a203ecbb1ede8883dc740f/kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/GwtLogEntry.java#L102

2022-07-11 07:47 UTC, marcellorinaldo requested changes

2022-07-11 07:47 UTC, marcellorinaldo commented on kura/org.eclipse.kura.log.filesystem.provider/src/main/java/org/eclipse/kura/log/filesystem/provider/KuraLogLineParser.java
> +                return new LogEntry(entryProperties, Long.parseLong(instance.timestamp.substring(0, 13)));
Kura log timestamps are strings in form "2022-07-11T09:32:06,540". `Long.parseLong` will fail every time.

We could do something like that:
```
try {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-ddThh:mm:ss,SSS");
    Date parsedDate = dateFormat.parse(instance.timestamp);
    return new LogEntry(entryProperties, new Timestamp(parsedDate));
} catch ...
```

2022-07-15 12:08 UTC, MMaiero commented
Could you give it a try in this version? Thanks

2022-07-15 12:42 UTC, marcellorinaldo reviewed
Shall we set `DEFAULT_TIMESTAMP` to the current date? In my previous contribution I set it to `new Date(0)`

2022-07-15 12:56 UTC, marcellorinaldo approved these changes
Verified as working on Raspberry Pi 4

2022-07-15 14:51 UTC, marcellorinaldo approved these changes

2022-07-16 07:21 UTC, merged