docs: add "Cloud Connection API and Usage" section
eclipse/kura pull request #4156
Opened 2022-09-13 07:42 UTC by mattdibi

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to inderstand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2022-09-13 14:14 UTC, marcellorinaldo commented
@mattdibi is this a work in progress?

2022-09-13 14:42 UTC, mattdibi commented
> @mattdibi is this a work in progress?

No, why?

2022-09-13 15:21 UTC, marcellorinaldo requested changes

2022-09-13 15:21 UTC, marcellorinaldo commented on docs/cloud-api/app-dev-guide.md
> +1. **Write component definition**
Enumeration will not work in this list if you don't indent the rest. Maybe those can be subsections.

2022-09-13 15:21 UTC, marcellorinaldo commented on docs/cloud-api/built-in-cloud.md
> +![](images/cloudService.png){ style="border-radius: 7px;"}
Some old screenshots, but I think we can keep them.

2022-09-13 15:21 UTC, marcellorinaldo commented on docs/cloud-api/overview.md
> +    public  KuraMessage doDel(RequestHandlerContext context, KuraMessage reqMessage) throws KuraException;
There is an extra space before KuraMessage

2022-09-13 15:21 UTC, marcellorinaldo commented on docs/cloud-api/user-guide.md
> +1. Open the Cloud Connections section of the Web UI:
Need to indent the image to have the enumeration working for the list. Please apply to the rest of the file

2022-09-14 08:57 UTC, mattdibi commented
@marcellorinaldo should be fixed now

2022-09-15 08:38 UTC, marcellorinaldo approved these changes

2022-09-15 08:39 UTC, merged