docs: added References section
eclipse/kura pull request #4169
Opened 2022-09-16 13:35 UTC by marcellorinaldo

Signed-off-by: Marcello Martina <martina.marcello.rinaldo@outlook.com>

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

This PR ports the References section from the old documentation.

**Related Issue:** N/A.

**Description of the solution adopted:** N/A.

**Screenshots:** N/A.

**Any side note on the changes made:** N/A.

2022-09-16 13:35 UTC, marcellorinaldo commented
@mattdibi can you please review?

2022-09-19 06:34 UTC, mattdibi requested changes

2022-09-19 06:34 UTC, mattdibi commented on docs/references/mqtt-namespace.md
> +For information about the OSGi Configuration Admin Service and the OSGi Meta Type Service, please refer to the [OSGi Service Platform Service Compendium 4.3 Specifications](http://www.osgi.org/Specif
404 link

2022-09-19 06:34 UTC, mattdibi commented on docs/references/mqtt-namespace.md
> +* The **Object Class Definition** (OCD), which describes the service attributes that may be configured. (The syntax of the OCD element is described in the [OSGi Service Platform Service Compendium 4.
404 link

2022-09-19 06:34 UTC, mattdibi commented on docs/references/mqtt-namespace.md
> +This operation provides configurations for a specific service that is identified by an OSGi service persistent identifier (**pid)**.
```suggestion
This operation provides configurations for a specific service that is identified by an OSGi service persistent identifier (**pid**).
```

2022-09-19 06:34 UTC, mattdibi commented on docs/references/mqtt-namespace.md
> +For information about the OSGi Deployment Admin Service, please refer to the [OSGi Service Platform Service Compendium 4.3 Specifications](http://www.osgi.org/Specifications/HomePage).
404 link

2022-09-19 10:19 UTC, mattdibi approved these changes

2022-09-19 10:24 UTC, merged