feat: added wire.script.tools
eclipse/kura pull request #4286
Opened 2022-12-02 16:25 UTC by GregoryIvo

Signed-off-by: Gregory Ivo <gregorybivo@gmail.com>

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2022-12-02 16:25 UTC, GregoryIvo commented
@marcellorinaldo What do you think?

2022-12-02 16:30 UTC, marcellorinaldo commented
TODO: update NOTICE file.

2022-12-02 16:31 UTC, marcellorinaldo commented
Pending EMO approval for org.graalvm.js/js/22.0.0.2 https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5271#note_1048938

2022-12-02 16:47 UTC, marcellorinaldo requested changes

2022-12-02 16:47 UTC, marcellorinaldo commented on kura/test/org.eclipse.kura.wire.script.tools.test/build.properties
> +# Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
Please correct copyright header

2022-12-02 16:47 UTC, marcellorinaldo commented on kura/test/org.eclipse.kura.wire.script.tools.test/pom.xml
> +			<plugin>
Please fix indentation

2022-12-02 22:02 UTC, GregoryIvo commented
Updated Example Script:

Script:
```
// the following global variables are available:
// input: an object that represents the received wire envelope
// output: an object that can be used for emitting records
// logger: a slf4j logger

// input has two properties:
// input.emitterPid contains the emitterPid of the received envelope
// input.getRecords() is an immutable array that contains the received records

logger.info('Emitter pid is {}', input.getEmitterPid())

var record = input.getRecords()[0].getProperties() // get the properties of the first record, it is assumed it comes from a Timer


// input records are immutable
// the properties of a record are TypedValues
logger.info('timer value: {}', record.TIMER.getValue()) // print the timer value
logger.info('timer value type: {}', record.TIMER.getType()) // print the timer value type



var records = input.getRecords()

for(let i=0; i<records.length; i++) {
    // WireRecord.getProperties() returns a map of String -> TypedValue
    for (const [keyString, typedValue] of records[i].getProperties()) {
        logger.info('The {}-th record contains:', String(i))
        logger.info('\t{}={}\n', keyString, typedValue.getValue())
    }
}

// creating a list of wire records to emit
var output = new Array()

// each WireRecord contains a map of properties
var outputMap = new Object()

// first record contains an integer
outputMap = new Object()
outputMap['example.integer'] = newIntegerValue(10)
outputMap['example.long'] = newLongValue(100)
outputMap['example.float'] = newFloatValue(1.014)
outputMap['example.double'] = newDoubleValue(10.12)
outputMap['example.boolean'] = newBooleanValue(true)
output[0] = newWireRecord(outputMap)

// second record contains a byte-array
var byteArray = newByteArray(4) 
byteArray[0] = 1
byteArray[1] = 2
byteArray[2] = 0xaa
byteArray[3] = 0xbb
outputMap = new Object()
outputMap['example.byte.array'] = newByteArrayValue(byteArray)
output[1] = newWireRecord(outputMap)

// third record contains strings
outputMap = new Object()
outputMap['example.string1'] = newStringValue('Hello World!')
outputMap['example.string3'] = newStringValue('Hello World Twice!')
outputMap['example.string2'] = newStringValue('Hello World Thrice!')
output[2] = newWireRecord(outputMap)


// the script context is retained across different
// invocations for a single ScriptFilter
// this allows stateful computations

// create a persistent counter
counter = typeof(counter) === 'undefined' ? 0 : counter
counter++

// emit the counter value in a different WireRecord
outputMap = new Object()
outputMap['counter'] = newIntegerValue(counter)
var counterRecord = newWireRecord(outputMap)
output.push(counterRecord)


logger.info('Records that will be emitted: {}', output.length)
```

Output:
```
2022-12-02T17:01:05,696 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger - Record List content:
2022-12-02T17:01:05,696 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -   Record content:
2022-12-02T17:01:05,696 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.integer : 10
2022-12-02T17:01:05,696 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.long : 100
2022-12-02T17:01:05,697 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.float : 1.014
2022-12-02T17:01:05,697 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.double : 10.12
2022-12-02T17:01:05,697 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.boolean : true
2022-12-02T17:01:05,697 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -   Record content:
2022-12-02T17:01:05,697 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.byte.array : [1, 2, 0, 0]
2022-12-02T17:01:05,697 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -   Record content:
2022-12-02T17:01:05,698 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.string1 : Hello World!
2022-12-02T17:01:05,698 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.string3 : Hello World Twice!
2022-12-02T17:01:05,698 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     example.string2 : Hello World Thrice!
2022-12-02T17:01:05,698 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -   Record content:
2022-12-02T17:01:05,698 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -     counter : 231
2022-12-02T17:01:05,698 [WiresTimer_timer_1767873417] INFO  o.e.k.i.w.l.Logger -
```

2022-12-03 12:46 UTC, MMaiero commented
Tests are either not picked up or not covering all the new code.

2022-12-03 12:48 UTC, GregoryIvo commented
@MMaiero seems to be not picked up. Tried to modify the sonar path in the main Pom, is there any other potential reason why this could happen?

2022-12-05 11:13 UTC, marcellorinaldo commented
Documentation: https://github.com/eclipse/kura/pull/4287

2022-12-05 13:17 UTC, marcellorinaldo submitted a review, later dismissed

2022-12-05 13:23 UTC, marcellorinaldo commented
Waiting for EMO approval: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5271#note_1048938

2022-12-05 17:05 UTC, GregoryIvo commented
@marcellorinaldo made the changes you suggested, please take a look!

2022-12-06 08:13 UTC, marcellorinaldo requested changes

2022-12-06 08:13 UTC, marcellorinaldo commented on kura/org.eclipse.kura.wire.script.tools/src/main/java/org/eclipse/kura/wire/script/tools/conditional/component/ConditionalComponent.java
> +        if (!result.isPresent()) {
This condition is never tested, i think it is an important test case.

2022-12-06 08:13 UTC, marcellorinaldo commented on kura/org.eclipse.kura.wire.script.tools/src/main/java/org/eclipse/kura/wire/script/tools/conditional/component/ConditionalComponent.java
> +        if (result.get().getType() != DataType.BOOLEAN) {
Also this condition is never tested. Can we add some cases on that too?

2022-12-06 10:08 UTC, GregoryIvo commented
note: we also need to fix the default script

2022-12-06 10:21 UTC, marcellorinaldo commented
> note: we also need to fix the default script

I've added the new default with this commit https://github.com/eclipse/kura/pull/4286/commits/599b92bfa4b9338c25bddb12b2f4db20bc3b59f7. I've tested it working, isn't it anymore?

2022-12-06 15:08 UTC, marcellorinaldo approved these changes

2022-12-12 08:18 UTC, marcellorinaldo commented
NOTICE file update: https://github.com/eclipse/kura/pull/4288

2022-12-12 08:19 UTC, merged