fix: changed decrypt passwords to false
eclipse/kura pull request #4317
Opened 2022-12-22 20:33 UTC by GregoryIvo

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR.

Fix a configurableComponents/configurations/byPid REST API error, where attempting to decode a password throws an error.

**Related Issue:** N/A

**Description of the solution adopted:** N/A

**Screenshots:** N/A

**Any side note on the changes made:** N/A

2022-12-22 22:22 UTC, GregoryIvo commented
Still working on the tests for this PR

2022-12-29 02:10 UTC, GregoryIvo commented
PR is now ready for review!

2022-12-29 15:39 UTC, MMaiero commented
I think we need to add tests to prevent regressions in the /byPid call.
I may have missed, but I think that tests now are not covering a password field in the /byPid or /byPid/_default, right?

2023-01-02 10:47 UTC, MMaiero requested changes
I think we need to add tests to prevent regressions in the /byPid call.
I may have missed, but I think that tests now are not covering a password field in the /byPid or /byPid/_default, right?

2023-01-02 13:14 UTC, GregoryIvo commented
> I think we need to add tests to prevent regressions in the /byPid call.
> 
> I may have missed, but I think that tests now are not covering a password field in the /byPid or /byPid/_default, right?

Seems to be so.

2023-01-04 21:02 UTC, GregoryIvo commented
After going over the tests, we may be good.  Let me know what you think?

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/29900100/210649201-a5be82ee-1172-437c-8a50-3bf84da4f4b5.png">

2023-01-06 08:00 UTC, MMaiero commented on kura/org.eclipse.kura.rest.configuration.provider/src/main/java/org/eclipse/kura/internal/rest/configuration/ConfigurationRestService.java
> +     *                                      provides all the parameters needed to
Can we double check the formatting here? Spacing seems odd. Are we using the Kura Formatter and cleanup profiles?

2023-01-06 08:00 UTC, MMaiero commented on kura/test/org.eclipse.kura.core.cloud.test/pom.xml
> +	<build>
same here.

2023-01-06 08:02 UTC, MMaiero commented
> After going over the tests, we may be good. Let me know what you think?
> 
> <img alt="image" width="1095" src="https://user-images.githubusercontent.com/29900100/210649201-a5be82ee-1172-437c-8a50-3bf84da4f4b5.png">

Yes, I see coverage. But do the test(s) that stresses those areas have a password field to verify the actual behaviour?

2023-01-06 15:00 UTC, GregoryIvo commented
1) attempted to reformat the suggested docs. They seem to be already formatted correctly. (nothing changed on my end, and pasting my current config settings for sanity check)
<img width="1890" alt="image" src="https://user-images.githubusercontent.com/29900100/211038085-6cafac2e-2c72-4fc3-955a-fbad8a66425d.png">

2) will make the tests.

2023-01-06 15:06 UTC, MMaiero commented
> 1. attempted to reformat the suggested docs. They seem to be already formatted correctly. (nothing changed on my end, and pasting my current config settings for sanity check)
> 
> <img alt="image" width="1890" src="https://user-images.githubusercontent.com/29900100/211038085-6cafac2e-2c72-4fc3-955a-fbad8a66425d.png">
> 
> 2. will make the tests.

Rethinking of it I believe the formatter covers just java code not xml. It may be that the xml is configured with tabs instead of spaces in your setup?
Maybe that can explain the change in the PR.

Thanks for 2).

2023-01-11 16:16 UTC, MMaiero commented
@GregoryIvo Can you please rebase so that we solve the conflict with the changes made in a previous PR? Thanks

2023-01-11 21:55 UTC, GregoryIvo commented
@MMaiero I have finally made the suggested tests, let me know what you think!

2023-01-12 08:10 UTC, MMaiero approved these changes

2023-01-12 08:11 UTC, merged