fix: updated target-platform to use newer version of protobuf
eclipse/kura pull request #4319
Opened 2022-12-29 13:35 UTC by GregoryIvo

Updated com.google.protobuf:protobuf-java ([Maven](https://github.com/advisories?query=ecosystem%3Amaven)) to mitigate [CVE-2022-3509](https://github.com/advisories/GHSA-g5ww-5jh7-63cx)

**Related Issue:** N/A

**Description of the solution adopted:** N/A

**Screenshots:**  N/A

**Any side note on the changes made:** N/A

2022-12-29 15:34 UTC, MMaiero commented
Please check also the following usages:
https://github.com/eclipse/kura/blob/bd9a1a05064eef959303b2b1f29aa19df8a944a5/kura/org.eclipse.kura.core.cloud/build.properties#L6
and 
https://github.com/eclipse/kura/blob/bd9a1a05064eef959303b2b1f29aa19df8a944a5/kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/build.properties#L5

Also, are the following references affected? Do we need to update also here? 
https://github.com/eclipse/kura/blob/b67d45a24561708bb276b2df6a0e94e112c041d1/kura/org.eclipse.kura.ai.triton.server/build.properties#L19
https://github.com/eclipse/kura/blob/b67d45a24561708bb276b2df6a0e94e112c041d1/kura/org.eclipse.kura.ai.triton.server/build.properties#L23

2022-12-29 15:36 UTC, GregoryIvo commented
> Please check also the following usages:
> 
> https://github.com/eclipse/kura/blob/bd9a1a05064eef959303b2b1f29aa19df8a944a5/kura/org.eclipse.kura.core.cloud/build.properties#L6
> 
> 
> and
> https://github.com/eclipse/kura/blob/bd9a1a05064eef959303b2b1f29aa19df8a944a5/kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/build.properties#L5
> 
> Also, are the following references affected? Do we need to update also here?
> 
> https://github.com/eclipse/kura/blob/b67d45a24561708bb276b2df6a0e94e112c041d1/kura/org.eclipse.kura.ai.triton.server/build.properties#L19
> 
> 
> https://github.com/eclipse/kura/blob/b67d45a24561708bb276b2df6a0e94e112c041d1/kura/org.eclipse.kura.ai.triton.server/build.properties#L23

Should I try moving these usages to the target platform?

2022-12-29 15:37 UTC, MMaiero commented
I would say not for now. We have an item in the backlog to check if we can use the target platform for that.

2022-12-30 01:35 UTC, GregoryIvo commented
@MMaiero  The .jars here are actually committed to the repo. I really want to set up the POM to fetch them compile time. Thoughts? Or should I just save this for the other backlog item?

2022-12-30 07:17 UTC, MMaiero commented
Agreed. Let's change the Pom so that is better maintainable

2023-01-04 12:51 UTC, mattdibi reviewed
LGTM overall. The CI is reporting some failures though, can you take a look at that?

2023-01-04 14:14 UTC, GregoryIvo commented
> LGTM overall. The CI is reporting some failures though, can you take a look at that?
> 
> ```
> [ERROR] Failed to execute goal on project org.eclipse.kura.container.orchestration.provider.test: Could not resolve dependencies for project org.eclipse.kura:org.eclipse.kura.container.orchestration.provider.test:eclipse-test-plugin:1.2.0-SNAPSHOT: Failed to collect dependencies at com.github.docker-java:docker-java-api:jar:3.2.12 -> org.slf4j:slf4j-api:jar:1.7.30: Failed to read artifact descriptor for org.slf4j:slf4j-api:jar:1.7.30: Could not transfer artifact org.slf4j:slf4j-api:pom:1.7.30 from/to kura_addons (https://kura-repo.s3.us-west-2.amazonaws.com/kura_addons/): Transfer failed for https://kura-repo.s3.us-west-2.amazonaws.com/kura_addons/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.pom: Unknown host kura-repo.s3.us-west-2.amazonaws.com: Temporary failure in name resolution -> [Help 1]
> ```

It's one of those strange errors, where the CI build only fails in the pipeline.  Trying to solve.

2023-01-04 15:51 UTC, mattdibi approved these changes

2023-01-04 16:14 UTC, GregoryIvo commented
I have pinged Milos to get a full QA on this, will report back when complete.

2023-01-09 11:17 UTC, mstankovic commented
I have been working on this build last two days and no errors found. Please keep in mind that I used Kura build for RPI and triton AI is not tested @GregoryIvo

2023-01-09 12:30 UTC, MMaiero commented
@mattdibi Can you please help us on the AI part?

2023-01-09 13:31 UTC, mattdibi commented
@MMaiero I'm on it... will report here when I get the results :)

2023-01-10 07:18 UTC, mattdibi commented
@GregoryIvo @MMaiero I'm having trouble instantiating the Triton Server Remote component on RPi 64bit. I'm getting the following:

```
2023-01-10T07:14:08,640 [qtp275306436-208] INFO  o.e.k.a.t.s.TritonServerServiceAbs - Activate TritonServerService...
2023-01-10T07:14:08,641 [qtp275306436-208] INFO  o.e.k.a.t.s.TritonServerServiceAbs - Update TritonServerService...
tail: /var/log/kura.log: file truncated
2023-01-10T07:15:08,660 [qtp275306436-208] WARN  o.e.j.s.h.C.ROOT - Exception while dispatching incoming RPC call
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @65986984
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
```

I'm using the installer provided by the CI build. IIRC this was causing trouble in the past so I'll switch to a local build.

Do not merge for now.

2023-01-10 07:56 UTC, mattdibi commented
I used a local build but I got the same results...

![image](https://user-images.githubusercontent.com/22748355/211493183-46298df2-98b2-4360-a7f9-f2454331a20c.png)

... the thing is... the exception is thrown even when setting the wrong password at login...

![image](https://user-images.githubusercontent.com/22748355/211493417-980f869c-e58d-4b41-bfc8-c7c5dcfe5e05.png)

What is going on here? Is this an unrelated problem?

2023-01-10 07:56 UTC, mattdibi requested changes
Investigate issues

2023-01-10 08:36 UTC, mattdibi commented
Ok so... after some more digging we found that the error reported [here](https://github.com/eclipse/kura/pull/4319#issuecomment-1376861234) was related to a known issue with running Kura on a Java 17 environment. There's a separate issue now that's tracking it.

Unfortunatly, after using the known fix, I still can't instantiate the Triton component due to the following error:

```
!ENTRY org.eclipse.kura.ai.triton.server 4 0 2023-01-10 07:51:44.892
!MESSAGE bundle org.eclipse.kura.ai.triton.server:1.2.0.202301100737 (192)[org.eclipse.kura.ai.triton.server.TritonServerRemoteService(85)] : The activate method has thrown an exception
!STACK 0
"kura-console.log" 2196 lines, 201916 bytes
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:340)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:756)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:440)
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:316)
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:118)
        at org.eclipse.equinox.internal.cm.EventDispatcher$1.run(EventDispatcher.java:92)
        at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:40)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap cannot be found by org.eclipse.kura.ai.triton.server_1.2.0.202301100737
        ... 35 more

!ENTRY org.eclipse.kura.ai.triton.server 4 0 2023-01-10 08:34:38.289
!MESSAGE bundle org.eclipse.kura.ai.triton.server:1.2.0.202301100737 (192)[org.eclipse.kura.ai.triton.server.TritonServerRemoteService(91)] : The activate method has thrown an exception
!STACK 0
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap
```

I'll now try using a Java 8 environment and see if the issue persists

2023-01-10 15:28 UTC, mattdibi commented
Commit 20be19fe397e59bdb86b3a64c64a708c6df4e9d6 seems to have fixed the issue.

I can correctly load a model from a remote Triton server through Kura.

![image](https://user-images.githubusercontent.com/22748355/211592488-38d19e81-8bd4-40d9-bd16-c1ef68a6fc91.png)

2023-01-10 15:48 UTC, GregoryIvo commented
@mattdibi  the git ignores have been added in commit: 
8d52f6d

2023-01-10 15:48 UTC, mattdibi approved these changes

2023-01-11 08:15 UTC, merged