docs(container.orchestrator): explain how to specify internet protocol at port
eclipse/kura pull request #4331
Opened 2023-01-17 19:33 UTC by GregoryIvo

updated documentation to include an explanation of how to specify what protocol to use at a container port.

**Related Issue:** N/A

**Description of the solution adopted:**  N/A
**Screenshots:**  N/A

**Any side note on the changes made:**  N/A

2023-01-17 19:34 UTC, GregoryIvo commented
@mattdibi  may you please review this, TY.  🧃

2023-01-18 07:47 UTC, mattdibi commented on docs/core-services/container-orchestration-provider-usage.md
> +- **Internal Ports** - This field accepts a comma-separated list of ports that will be internally exposed on the spun-up container. In this field, you can also specify which protocol to run at the po
As you know I'm a big fan of the markdown code rendering XD

```suggestion
- **Internal Ports** - This field accepts a comma-separated list of ports that will be internally exposed on the spun-up container. In this field, you can also specify which protocol to run at the port by appending a port with a colon and typing in the name of the network protocol. Example: `80, 443:tcp, 8080:udp`.
```

2023-01-18 07:48 UTC, mattdibi requested changes
See comment

2023-01-18 07:48 UTC, mattdibi approved these changes

2023-01-18 07:49 UTC, merged