build: Commit ignored files to fix Docker
eclipse/kura pull request #4400
Opened 2023-02-22 16:58 UTC by GregoryIvo

This PR resolves build issues with the last docker build fix.

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2023-02-22 18:19 UTC, GregoryIvo commented
Current Build output After these changes:
```
[INFO] --- maven-antrun-plugin:1.7:run (docker-x86_64-nn-build-container) @ distrib ---
[INFO] Executing tasks

main:
     [copy] Copying 1 file to /Users/eurotech/workspaces/Kura/kura/kura/distrib/target
     [exec] STEP 1/2: FROM scratch AS builder
     [exec] STEP 2/2: COPY . /kura-install/
     [exec] COMMIT base-kura-docker:5.3.0-SNAPSHOT
     [exec] --> Pushing cache []:30ea76b7b219015c7606151729e0ed1e2f753be4ef65800a40356d2c44daca94
     [exec] --> c86fc06b132
     [exec] Successfully tagged localhost/base-kura-docker:5.3.0-SNAPSHOT
     [exec] Successfully tagged localhost/base-kura-docker-x86_64:5.3.0-SNAPSHOT
     [exec] c86fc06b132e3d0b86bd480fc9852bd4c9cbbcf8d5be0ed8283a2e9811ae3985
[INFO] Executed tasks
[INFO] 
[INFO] --- jdeb:1.0:jdeb (docker-x86_64-nn-deb) @ distrib ---
[INFO] Creating debian package: /Users/eurotech/workspaces/Kura/kura/kura/distrib/target/kura_5.3.0-SNAPSHOT_docker-x86_64-nn_installer.deb
[INFO] Building data
[INFO] file:./tmp/kura_5.3.0-SNAPSHOT_docker-x86_64-nn.zip size:100453812 mode:33188 linkname: username:root userid:0 groupname:root groupid:0 modtime:Wed Feb 22 13:15:54 EST 2023 md5: 3535ce5c623d28eacb3e5c5c324c73cc
[INFO] Total size: 100453812
[INFO] Building control
[INFO] Attaching created debian archive /Users/eurotech/workspaces/Kura/kura/kura/distrib/target/kura_5.3.0-SNAPSHOT_docker-x86_64-nn_installer.deb
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (docker-ubi8-x86_64-nn-build-container) @ distrib ---
STEP 1/11: FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
Trying to pull registry.access.redhat.com/ubi8/ubi-minimal:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:c7e856e037412834d0faf555c76b9f9f0e598353b704888a6d3effc0138aa243
Copying config sha256:66e192fc4d3f62ae13139fa507d17e21516887ab8eda660411d740ff3535ae93
Writing manifest to image destination
Storing signatures
STEP 2/11: MAINTAINER Eclipse Kura Developers <kura-dev@eclipse.org>
--> Pushing cache []:c3111df422b295caa8992de204820719692fd46624bffd505bd2c1c4eba93042
--> 42c1bc2fb22
STEP 3/11: LABEL maintainer="Eclipse Kura Developers <kura-dev@eclipse.org>"       io.k8s.description="Containerized version of the Eclipse Kura™ IoT gateway"       io.openshift.non-scalable=true
--> Pushing cache []:bd6795418d57b33f9d70ea39afb5af5fc56af102d66bca28177c5afb24b36409
--> bfa78de3486
STEP 4/11: ARG BASE_IMAGE_KURA='kura-base:latest'
--> Pushing cache []:55cc38d72c98b5bdc46b99313bc96fc9354d11a294be37ab57e78cef9c26e93a
--> 822193deda0
STEP 5/11: COPY bin/ /usr/local/bin/
--> Pushing cache []:932fc064cfee1200a4086cb1a1735be08eb70f0680553928c2d8c5c49199c859
--> d73a141a2c5
STEP 6/11: COPY --from=${BASE_IMAGE_KURA} /kura-install/kura_*_docker-x86_64-nn_installer.sh /kura-install/
--> Pushing cache []:a0cc8279532caf69fcbe55efc9586be517034bc5342066d14e35d328c57fc035
--> f43be2be87e
STEP 7/11: ENV   KURA_DIR=/opt/eclipse/kura   JAVA_HOME=/usr/lib/jvm/jre-1.8.0   SKIP_JAVA_VERSION_CHECK=true   LAUNCHER_VERSION="1.5.800.v20200727-1323"
--> Pushing cache []:2756b09035541eb35e186a332a2e4df9bceb542ce3dde60f1f6130122076e1eb
--> 9be60df0592
STEP 8/11: RUN true &&     rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm &&     microdnf -y update &&     microdnf -y install         java-1.8.0-openjdk-headless         procps         zip         unzip         gzip         tar         psmisc         socat         dos2unix         openssl         net-tools         hostname         which         findutils     &&     microdnf -y clean all && rm -rf /var/cache/yum &&     /kura-install/kura_*_docker-x86_64-nn_installer.sh && rm -rf /kura-install/ &&     chmod a+rw -R /opt/eclipse &&     find /opt/eclipse -type d | xargs chmod a+x &&     chmod a+rwx /var/log &&     `# Test for the existence of the entry point`     test -x "${KURA_DIR}/bin/start_kura.sh" &&     chmod a+x -R /usr/local/bin/ &&     install -m 0777 -d "${KURA_DIR}/data" &&     mkdir -p ${KURA_DIR}/packages &&     if [ "$PACKED" == "true" ]; then touch /kura.packed && sh pack-kura; fi  &&     chmod +x /usr/local/bin/*  &&     unpack-kura  &&     dp-install "https://repo1.maven.org/maven2/de/dentrassi/kura/addons/de.dentrassi.kura.addons.utils.fileinstall/0.6.0/de.dentrassi.kura.addons.utils.fileinstall-0.6.0.dp"  &&     add-config-ini "felix.fileinstall.disableNio2=true"  &&     add-config-ini "felix.fileinstall.dir=/load"  &&     pack-kura
warning: /var/tmp/rpm-tmp.SjeEos: Header V4 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Verifying...                          ########################################
Preparing...                          ########################################
Updating / installing...
epel-release-8-18.el8                 ########################################
Many EPEL packages require the CodeReady Builder (CRB) repository.
It is recommended that you run /usr/bin/crb enable to enable the CRB repository.

(microdnf:8): librhsm-WARNING **: 18:16:15.748: Found 0 entitlement certificates

(microdnf:8): librhsm-WARNING **: 18:16:15.760: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Nothing to do.

(microdnf:69): librhsm-WARNING **: 18:16:23.273: Found 0 entitlement certificates

(microdnf:69): librhsm-WARNING **: 18:16:23.275: Found 0 entitlement certificates
Package                                                          Repository               Size
Installing:                                                                                   
 acl-2.2.53-1.el8.x86_64                                         ubi-8-baseos-rpms     83.0 kB
 avahi-libs-0.7-20.el8.x86_64                                    ubi-8-baseos-rpms     63.1 kB
 copy-jdk-configs-4.0-2.el8.noarch                               ubi-8-appstream-rpms  31.3 kB
 cracklib-2.9.6-15.el8.x86_64                                    ubi-8-baseos-rpms     95.5 kB
 cracklib-dicts-2.9.6-15.el8.x86_64                              ubi-8-baseos-rpms      4.1 MB
 crypto-policies-scripts-20211116-1.gitae470d6.el8.noarch        ubi-8-baseos-rpms     85.2 kB
 cryptsetup-libs-2.3.7-2.el8.x86_64                              ubi-8-baseos-rpms    499.4 kB
 cups-libs-1:2.2.6-50.el8.x86_64                                 ubi-8-baseos-rpms    445.1 kB
 dbus-1:1.12.8-23.el8_7.1.x86_64                                 ubi-8-baseos-rpms     43.1 kB
 dbus-common-1:1.12.8-23.el8_7.1.noarch                          ubi-8-baseos-rpms     47.9 kB
 dbus-daemon-1:1.12.8-23.el8_7.1.x86_64                          ubi-8-baseos-rpms    246.8 kB
 dbus-libs-1:1.12.8-23.el8_7.1.x86_64                            ubi-8-baseos-rpms    189.3 kB
 dbus-tools-1:1.12.8-23.el8_7.1.x86_64                           ubi-8-baseos-rpms     88.3 kB
 device-mapper-8:1.02.181-6.el8.x86_64                           ubi-8-baseos-rpms    386.5 kB
 device-mapper-libs-8:1.02.181-6.el8.x86_64                      ubi-8-baseos-rpms    419.7 kB
 diffutils-3.6-6.el8.x86_64                                      ubi-8-baseos-rpms    367.4 kB
 dos2unix-7.4.0-3.el8.x86_64                                     ubi-8-baseos-rpms    246.5 kB
 elfutils-default-yama-scope-0.187-4.el8.noarch                  ubi-8-baseos-rpms     52.9 kB
 elfutils-libs-0.187-4.el8.x86_64                                ubi-8-baseos-rpms    304.1 kB
 expat-2.2.5-10.el8_7.1.x86_64                                   ubi-8-baseos-rpms    116.2 kB
 findutils-1:4.6.0-20.el8.x86_64                                 ubi-8-baseos-rpms    540.8 kB
 freetype-2.9.1-9.el8.x86_64                                     ubi-8-baseos-rpms    403.3 kB
 gdbm-1:1.18-2.el8.x86_64                                        ubi-8-baseos-rpms    132.8 kB
 gdbm-libs-1:1.18-2.el8.x86_64                                   ubi-8-baseos-rpms     61.8 kB
 gzip-1.9 [...]

2023-02-22 18:42 UTC, GregoryIvo commented
@marcomatteo  @salvatore-coppola  Looks like everything is working here now!

2023-02-22 23:54 UTC, GregoryIvo commented
After these changes it now appears to be building well on my Linux box 🤞

2023-02-23 12:00 UTC, MMaiero commented
Tested and verified as correctly building on my end @mstankovic can you please check if it works for you?
You need to build kura as usual and then run the following command to run the docker build:
```
mvn -f kura/distrib/pom.xml clean install -DbuildAllContainers
```

2023-02-27 07:32 UTC, mattdibi commented on README.md
> +### Building Eclipse Kura Docker/Podman Containers
I feel like "Kura Container" is descriptive enough.

```suggestion
### Building Eclipse Kura Containers
```

2023-02-27 07:39 UTC, mattdibi commented on README.md
> +
This instructions are already explained [here](https://github.com/eclipse/kura#build-kura). There's no need to repeat ourselves. Just reference them.

```suggestion
Build Kura as per [our instructions](https://github.com/eclipse/kura#build-kura). To build the containers you'll need to change the target of the "Build the target profiles" step like the following:

```

2023-02-27 07:40 UTC, mattdibi commented on README.md
> +After this command runs, images can be found in your docker/podman image list.
```suggestion
After this command runs, images can be found in your preferred container engine image list.
```

2023-02-27 07:41 UTC, mattdibi commented on README.md
> +
Redundant, we already explained that in: https://github.com/eclipse/kura#build-kura

```suggestion
```

2023-02-27 08:17 UTC, mattdibi requested changes
In addition to my comments, it might be useful to add that, if you have installed a container engine different from Docker on your system, you'll need to add an alias for the build to succeed. Example:

```bash
alias docker=podman
```

2023-02-27 09:01 UTC, mattdibi commented
Two more thoughts:
- What happens if you try to build the containers on an Arm machine? We should link documentation about multi-arch support (take a look [here](https://docs.docker.com/desktop/multi-arch/))
- Is [this documentation](https://github.com/eclipse/kura/blob/develop/kura/container/README.md) still valid? Should this get updated or deleted?

Feel free to create a new PR if you think it is outside the scope of this PR.

2023-02-28 17:23 UTC, GregoryIvo commented
> * this documentation

- the current build system only supports building on x86 targets. This multi arch investigation is probably better suited for another PR. (I would love to do it :D )
- changes to that documentation are made in pr #4402

2023-03-01 07:41 UTC, mattdibi approved these changes

2023-03-01 21:22 UTC, merged