fix(nm): Fixed plug of new network devices
eclipse/kura pull request #4407
Opened 2023-02-23 15:43 UTC by pierantoniomerlino

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

When a new network device is plugged into the device, the webUI search for a configuration in to the `NetworkConfigurationService`. If this is not present (and this is the case of new devices), a generic configuration object is returned. Since this can be an issue for wifi or modem interfaces, this PR modifies the logic returning an object of the correct type.

2023-02-23 16:28 UTC, mattdibi commented
Tested on RPi.

**Before this PR**:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/22748355/220968664-b4082f14-564d-4f67-9c91-523c42c5b07d.png">


<details>
<summary>
<code>2023-02-23T16:22:55,636 [qtp600529253-1599] WARN  o.e.j.s.h.C.ROOT - Exception while dispatching incoming RPC call com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.ArrayList org.eclipse.kura.web.shared.service.GwtStatusService.getDeviceConfig(org.eclipse.kura.web.shared.model.GwtXSRFToken,boolean,boolean) throws org.eclipse.kura.web.shared.GwtKuraException' threw an unexpected exception: java.lang.ClassCastException: org.eclipse.kura.web.shared.model.GwtNetInterfaceConfig cannot be cast to org.eclipse.kura.web.shared.model.GwtWifiNetInterfaceConfig</code>
</summary>

```bash
2023-02-23T16:22:55,636 [qtp600529253-1599] WARN  o.e.j.s.h.C.ROOT - Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.ArrayList org.eclipse.kura.web.shared.service.GwtStatusService.getDeviceConfig(org.eclipse.kura.web.shared.model.GwtXSRFToken,boolean,boolean) throws org.eclipse.kura.web.shared.GwtKuraException' threw an unexpected exception: java.lang.ClassCastException: org.eclipse.kura.web.shared.model.GwtNetInterfaceConfig cannot be cast to org.eclipse.kura.web.shared.model.GwtWifiNetInterfaceConfig
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.processCall(OsgiRemoteServiceServlet.java:208)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.eclipse.kura.web.server.OsgiRemoteServiceServlet.service(OsgiRemoteServiceServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.HttpServiceRuntimeImpl$LegacyServlet.service(HttpServiceRuntimeImpl.java:1459)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:159)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:67)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.dispatch(ProxyServlet.java:147)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.preprocess(ProxyServlet.java:115)
	at org.eclipse.equinox.http.servlet.internal.servlet.ProxyServlet.service(ProxyServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHttpServiceServlet.service(HttpServerManager.java:305)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassCastException: org.eclipse.kura.web.shared.model.GwtNetInterfaceConfig cannot be cast to org.eclipse.kura.web.shared.model.GwtWifiNetInterfaceConfig
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.getNetworkStatus(GwtStatusServiceImpl.java:322)
	at org.eclipse.kura.web.server.GwtStatusServiceImpl.getDeviceConfig(GwtStatusServiceImpl.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	... 53 more
```
</details>

**After this PR**:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/22748355/220969108-c59e8850-2c6a-4d59-a3a0-d30de6561d6b.png">

2023-02-23 16:28 UTC, mattdibi approved these changes

2023-02-23 16:31 UTC, mattdibi requested changes
There's a regression in the GUI.

After switching to the unconfigured device the data reported by the GUI stays to the last visited configured interface.

Opening the Chrome console I found the following:

<img width="1769" alt="image" src="https://user-images.githubusercontent.com/22748355/220974029-4d9ea6f0-1b34-489b-a2b7-ca9f319a02e5.png">

2023-02-24 13:45 UTC, pierantoniomerlino commented
@mattdibi The issue is not present with ethernet interfaces.

2023-02-27 11:07 UTC, mattdibi commented
Tested with your changes on top of #4406. Working great 👍 

![image](https://user-images.githubusercontent.com/22748355/221547986-aad2f772-96a4-4a0d-9e0d-8204a3405aae.png)
![image](https://user-images.githubusercontent.com/22748355/221548021-56dd1a78-bf44-46ad-b252-ecd88c155c65.png)

2023-02-27 11:07 UTC, mattdibi approved these changes

2023-02-27 11:11 UTC, pierantoniomerlino commented
Both the build and Sonar checks succeeded, but it fails to report the report:

```
org.sonarqube.ws.client.HttpException: Error 404 on https://sonarcloud.io/api/ce/task?id=AYaEuVK6xDAPM1mS2x0X : {"errors":[{"msg":"Project doesn\u0027t exist"}]}
```

2023-02-27 13:18 UTC, merged