test(nm): initial test coverage for NMDbusConnectorTest
eclipse/kura pull request #4408
Opened 2023-02-23 22:20 UTC by GregoryIvo

This PR adds initial test coverage for the NMDbusConnector Class.

a Rebased version of #4385.

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2023-02-23 22:43 UTC, GregoryIvo commented
@mattdibi  Ready for Review! 😄

2023-02-24 03:02 UTC, GregoryIvo commented
@mattdibi, I am now seeing that the coverage doesn't cover the new enums we made 😭.
Can we jump in a call tomorrow and do that fancy VIM macros to blaze though the test cases?

2023-02-24 07:26 UTC, mattdibi commented
> @mattdibi, I am now seeing that the coverage doesn't cover the new enums we made 😭. Can we jump in a call tomorrow and do that fancy VIM macros to blaze though the test cases?

Can't say no to some Vim macros flexing 😆 

BTW take a look at what Sonar is suggesting: looks like it doesn't like all the `eq(...)` you put in the tests.

2023-02-24 16:41 UTC, mattdibi commented
Sonar is reporting issues with the use of `eq(...)` but it doesn't compile without them. I'm going to write it off as a false positive.

2023-02-24 16:47 UTC, GregoryIvo commented
https://sonarsource.atlassian.net/browse/RSPEC-6073

^ This issue on actual sonar agrees with our opinion on the false positive

2023-02-24 16:50 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +
Remove the use of `@Before` such that we are more Gerkhin style compliant

 ```suggestion
    @After
    public void tearDown() {
        resetSingleton(NMDbusConnector.class, "instance");
    }

    public static <T> void resetSingleton(Class<T> clazz, String fieldName) {
        Field instance;
        try {
            instance = clazz.getDeclaredField(fieldName);
            instance.setAccessible(true);
            instance.set(null, null);
            instance.setAccessible(false);
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }

    @Test
    public void getDbusConnectionShouldWork() throws DBusException {
        givenBasicMockedDbusConnector();
        whenGetDbusConnectionIsRun();

```

2023-02-24 16:52 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        whenGetInterfaces();
```suggestion
        whenGetInterfacesIsCalled();
```

2023-02-24 16:52 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        whenApply();
```suggestion
        whenApplyIsCalled();
```

2023-02-24 16:52 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        thenNetoworkSettingsDoNotChangeForDevice("eth0");
```suggestion
        thenNetworkSettingsDoNotChangeForDevice("eth0");
```

2023-02-24 17:05 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +            hasNullPointerExceptionThrown = true;
Delete the stack traces prints

2023-02-24 17:05 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +            hasNullPointerExceptionThrown = true;
Also here:

```suggestion
            hasDBusExceptionBeenThrown = true;
        } catch (NoSuchElementException e) {
            hasNoSuchElementExceptionThrown = true;
        } catch (NullPointerException e) {
            hasNullPointerExceptionThrown = true;
```

2023-02-24 17:06 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        assertFalse(hasNoSuchElementExceptionThrown);
You forgot about the NPE exception:

```suggestion
        assertFalse(hasNoSuchElementExceptionThrown);
        assertFalse(hasNullPointerExceptionThrown);
```

2023-02-24 17:07 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +
Obsolete

```suggestion
```

2023-02-24 17:08 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +    public void thenConnectDisconnectIsCalledFor(String netInterface) throws DBusException {
```suggestion
    public void thenConnectionUpdateIsCalledFor(String netInterface) throws DBusException {
```

2023-02-24 17:10 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        verify(this.mockDevices.get(netInterface), never()).Disconnect();
You should also check that the `NetworkManager.ActivateConnection` and `NetworkManager.AddAndActivateConnection` are not called.

2023-02-24 17:18 UTC, mattdibi requested changes
You didn't check for cases where `NetworkManager.ActivateConnection` and `NetworkManager.AddAndActivateConnection` are called.

See: https://github.com/eclipse/kura/blob/4761495d41f8fbad2beeeb40e66c141b074b0e1d/kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java#L239-L248

2023-02-24 17:20 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +    public void givenMockedDevice(String interfaceName, NMDeviceType type, NMDeviceState state) throws DBusException {
For easier testing of devices without an associated connection I would suggest you to add a parameter here:

```suggestion
    public void givenMockedDevice(String interfaceName, NMDeviceType type, NMDeviceState state, boolean hasAssociatedConnection) throws DBusException {
```

2023-02-27 13:54 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
> +
Remove the extra space such that there's no change in `NMDbusConnector`.

```suggestion
```

2023-02-27 13:58 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDeviceStateTest.java
> +    public void whenNMDeviceStateStateIsPassed(NMDeviceState state) {
Some mishap with the rename method tool:

```suggestion
    public void whenNMDeviceStateIsPassed(NMDeviceState state) {
```

2023-02-27 14:06 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        thenGetDbusConnectionIsMockedConnection();
I prefer:

```suggestion
        thenGetDbusConnectionReturns(this.dbusConnection);
```

for readability reasons but there's no need to change it. Leave it as is if you prefer this way.

2023-02-27 14:16 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        thenNetworkManagerCalledActivateConnection("eth0");
For consistency I would prefer something like:

```suggestion
        thenActivateConnectionWasCalledFor("eth0");
```

2023-02-27 14:17 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        thenNetworkManagerCalledAddAndActivateConnection("eth0");
Again, for consistency:

```suggestion
        thenAddAndActivateConnectionIsCalledFor("eth0");
```

2023-02-27 14:20 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        thenNetworkSettingsDoNotChangeForDevice("wlan0");
Consistency: the other methods use the past tense. Use either the present tense or the past tense not both.

```suggestion
        thenNetworkSettingsDidNotChangeForDevice("eth0");
        thenNetworkSettingsDidNotChangeForDevice("wlan0");
```

2023-02-27 14:22 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        thenReturnedDevicesAre(Arrays.asList("wlan0", "eth0"));
Present tense or past tense?

```suggestion
        thenGetInterfacesReturned(Arrays.asList("wlan0", "eth0"));
```

2023-02-27 14:28 UTC, mattdibi requested changes
Apart for some small inconsistencies in method names everything looks great! GJ @GregoryIvo 

Try and take a look at my comments and see what makes sense for some more consistent naming.

After this round of changes I think we're ready to merge

2023-02-27 17:02 UTC, mattdibi commented
Supersided by #4414 and #4415

2023-02-27 17:02 UTC, closed without merging