fix: nm crash when fetch HWAddress on versions 1.24 or less
eclipse/kura pull request #4438
Opened 2023-03-09 22:32 UTC by GregoryIvo

This PR fixes a bug that occurs when trying to run kuraNM with a version of Network Manager 1.24 or less.

Introduces a new class called D

>  **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2023-03-09 22:35 UTC, GregoryIvo commented
@mattdibi  check out this PR pls!

2023-03-10 04:25 UTC, GregoryIvo commented
It doesn't explode on my end!

2023-03-10 07:35 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
> +            // new EthernetProperties(deviceProperties);
Leftover comment?

```suggestion
```

2023-03-10 07:41 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/DevicePropertiesWrapper.java
> +public class DevicePropertiesWrapper {
I like this a lot! Much better than my solution 👍

2023-03-10 07:52 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
> +            logger.debug("NetworkManager version equal or lower then 1.24 detected.");
This is not completely correct: the property is not available for NM versions <1.24. It is available for 1.24!

```suggestion
            logger.debug("NetworkManager version lower then 1.24 detected.");
```

2023-03-10 08:03 UTC, mattdibi commented
BTW @GregoryIvo you're trying to merge *your `develop`* branch onto Kura `develop`.... you might want to change that...

2023-03-10 08:47 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
> +                        devicePropertiesWrapper.getDeviceProperties().Get(NM_DEVICE_WIRED_BUS_NAME, NM_HW_ADDRESS)));
Did you notice that you didn't call the correct method here (i.e. `getDeviceSpecificProperties`) and it works anyway? 😄 

We noticed this behaviour only recently: when you call a `Get` it behaves sort of like a cast to the objec type represented by the BUS name.

So... if you have the `Device` properties, you can perform a `Get` to the `Device.Wireless` properties, without carrying around the specific `Properties` themselves.

RTFM I guess... 😆 

For now let's keep using the `Wrapper` and the device specific properties. We'll think about refactoring the `NMStatusConverter`using this behaviour later (for example for when we'll have the unit tests for the converter... see #4418 )

2023-03-10 09:12 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
> +        }
This is not how I would approach the issue.

1. I would emphasise with the code that we change how we get the hwAddress based on the version.
2. There's not actually a mapping between `NMDeviceType` and how we get the address, but on the builder type
3. I would emphasise with the code that we change how we get the hwAddress based on the builder type
4. You did not check if the `Optional` property is present or not.

Therefore:

```suggestion
String hwAddress = "";
        try {
            hwAddress = devicePropertiesWrapper.getDeviceProperties().Get(NM_DEVICE_BUS_NAME, NM_HW_ADDRESS);
        } catch (DBusExecutionException e) {
            logger.debug("NetworkManager version lower then 1.24 detected.");
        }

        if (hwAddress.isEmpty()) {
            // Fallback for NM version < 1.24
            if (!devicePropertiesWrapper.getDeviceSpecificProperties().isPresent()) {
                throw new IllegalArgumentException("No device specific properties found. Cannot retrieve HwAddress");
            }

            if (builder instanceof EthernetInterfaceStatusBuilder) {
                hwAddress = devicePropertiesWrapper.getDeviceSpecificProperties().get().Get(NM_DEVICE_WIRED_BUS_NAME,
                        NM_HW_ADDRESS);
            } else if (builder instanceof WifiInterfaceStatusBuilder) {
                hwAddress = devicePropertiesWrapper.getDeviceSpecificProperties().get().Get(NM_DEVICE_WIRELESS_BUS_NAME,
                        NM_HW_ADDRESS);
            } else { // Loopback
                hwAddress = "00:00:00:00:00:00";
            }
        }

        builder.withHardwareAddress(getMacAddressBytes(hwAddress));
```

2023-03-10 09:16 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
> +    private static final String NM_HW_ADDRESS = "HwAddress";
For consistency use the already established naming convention:

```suggestion
    private static final String NM_DEVICE_PROPERTY_HW_ADDRESS = "HwAddress";
```

2023-03-10 09:20 UTC, mattdibi requested changes
See comments

2023-03-10 09:39 UTC, mattdibi commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
> +        }
My goal here is to make it easier to refactor the code for when we'll have the version parsing (i.e. when we will be able to check `if(NM_VERSION.lowerThan("1.24"))` )

2023-03-10 16:10 UTC, GregoryIvo commented
After the changes, all seems to be working on my end!

2023-03-10 16:46 UTC, mattdibi approved these changes

2023-03-10 16:47 UTC, mattdibi commented
Tested on RPi with NM 1.30.6: all good.

2023-03-11 08:37 UTC, mattdibi commented
As always:

```
org.sonarqube.ws.client.HttpException: Error 404 on https://sonarcloud.io/api/ce/task?id=AYbNPD6A4tZUggCHEUqu : {"errors":[{"msg":"Project doesn\u0027t exist"}]}
	at hudson.plugins.sonar.client.HttpClient.getHttp(HttpClient.java:48)
	at hudson.plugins.sonar.client.WsClient.getCETask(WsClient.java:51)
```

Merging anyway. Sonar status is ok.

2023-03-11 08:37 UTC, merged