feat(web2): added automatic channel selection support for WiFi on net2
eclipse/kura pull request #4448
Opened 2023-03-14 10:55 UTC by marcellorinaldo

This PR allows to select `Automatic` in the channel field; which corresponds to channel 0 with frequency 0. This makes it compatible with [NM](https://networkmanager.dev/docs/api/latest/nm-settings-dbus.html), which allows ACS by setting channel to 0.

**Related Issue:** N/A.

**Description of the solution adopted:** N/A.

**Screenshots:** ACS:
<img width="729" alt="Screenshot 2023-03-14 at 11 52 24" src="https://user-images.githubusercontent.com/39562568/224979048-7448dedd-4599-4655-b12b-3c4c0a480810.png">

**Any side note on the changes made:** N/A.

2023-03-15 14:25 UTC, mattdibi requested changes
Multiple bugs found:
- UI always report "automatic" channel
- After a few settings the wifi interface gets disabled on its own

Some further debugging is required

2023-03-16 15:53 UTC, marcellorinaldo commented
@mattdibi Made some fixes and now it should be working.

2023-03-17 16:04 UTC, mattdibi commented
Tested on RPi 4 with NM 1.30.6. Everything working as expected.

AP mode:
- Setting the band and the channel, the AP is correctly set
- Setting the band and the automatic channel, the AP is set to the first available channel for that band
- Setting the channel and the band as 2.4/5 result in the channel dictating the band as expected.
- Setting the band as 2.4/5 and the channel as automatic result in the AP to be set in the first channel of the 2.4band and advertising as 802.11n

Station mode:
- Setting the band as 2.4/5 and the channel as automatic, if the remaining parameters are correct the device connects to the AP as expected.

2023-03-17 16:09 UTC, mattdibi approved these changes

2023-03-17 16:11 UTC, mattdibi requested changes
Nevermind

2023-03-17 16:12 UTC, mattdibi approved these changes

2023-03-17 16:50 UTC, merged