docs(linux.clock) Added some notes on ntpd and chrony
eclipse/kura pull request #4641
Opened 2023-05-11 14:17 UTC by salvatore-coppola

Added clarifications on some fields.

2023-05-11 15:08 UTC, marcellorinaldo requested changes
I have highlighted some mispellings

2023-05-11 15:08 UTC, marcellorinaldo commented on kura/org.eclipse.kura.linux.clock/OSGI-INF/metatype/org.eclipse.kura.clock.ClockService.xml
> +            description="Source for setting the system clock. Verify the availabiliy of the selected provider before activate it. Using crony-advace causes all fields, except Chrony Configuratio, to
crony-advace -> chrony-advanced
Configuratio -> Configuration

2023-05-12 11:42 UTC, MMaiero commented
@salvatore-coppola The PR title action fails. 
In addition to that, do we need to update the project's documentation page with the updated descriptions?

2023-05-16 07:16 UTC, marcellorinaldo approved these changes

2023-05-16 14:50 UTC, merged