feature: Added trigger scan button
eclipse/kura pull request #4791
Opened 2023-08-02 14:58 UTC by salvatore-coppola

Added the capability to force a wireless networks refresh with a button in the SSID Modal window.

Furthermore polkit rule and dbuse authorization have been added in order to use the wpasupplicant api on dbus

2023-08-02 15:49 UTC, mattdibi requested changes, later dismissed
About the NMDbusConnector changes:

I think the rescan should be ran only if the device is a WiFi interface. As of right now I think you’ll get an exception thrown if the recompute is requested for a different device.

I think you just need to move the wpa supplicant call inside here https://github.com/eclipse/kura/blob/f1859f1c7ea5bf2c6c8581ed020849b00ec4584d/kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java#L241

Furthermore I wouldn’t instantiate the wpa_supplicant wrapper at every net status request but rather add it as a private member of the NMDbusConnector as we did for all the other wrappers.

2023-08-03 08:42 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +        .thenReturn(this.mockedInterface);
This is not the correct way to mock the device. You should create and return the dbus path only for Wifi Devices and only for the interfaceId you expect.

```suggestion
        
        when(this.dbusConnection.getRemoteObject(eq("fi.w1.wpa_supplicant1"),
                eq("/fi/w1/wpa_supplicant1"), any())).thenReturn(this.mockedWpaSupplicant);
        
```

You should mock the interface in the [`givenMockedDevice` method](https://github.com/eclipse/kura/blob/177821520ceb573539fd6f0aad461990a98d0ec5/kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java#L986) where you can mock the interface only for WiFi devices:

https://github.com/eclipse/kura/blob/177821520ceb573539fd6f0aad461990a98d0ec5/kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java#L1017

There you'll have:

```java
    if (type == NMDeviceType.NM_DEVICE_TYPE_WIFI) {

        DBusPath fakeDbusInterfacePath = new DBusPath("/fake/dbus/path");
        
        when(this.mockedWpaSupplicant.GetInterface(interfaceId)).thenReturn(fakeDbusInterfacePath);
        
        when(this.dbusConnection.getRemoteObject(eq("fi.w1.wpa_supplicant1"), eq(fakeDbusInterfacePath.getPath()), any()))
        .thenReturn(this.mockedInterface);

         simulateIwCommandOutputs(interfaceId, mockedProperties1);
}
```

2023-08-03 09:41 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/NetworkStatusService.java
> +     *
I'd would like to use the same javadoc of the `getNetworkStatus(String interfaceId)` method, adding a comment regarding the recompute parameter.

2023-08-03 14:35 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +    private final Interface mockedInterface = mock(Interface.class);
As I said in my previous comment this is not correct. There's only one interface for the entire test.

Please, refer to how we handled the Device here:

https://github.com/eclipse/kura/blob/805c45b5e2ee8b258d192bb589762987494fa7a3/kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java#L121

You should have:
```suggestion
    private final Map<String, Interface> mockedInterfaces = new HashMap<>();
```

and in the `givenMockedDevice` code **create** the mock interface adding it to the above mentioned map for tracking.

Later in the `then` method you'll check the expectation using the "interfaceId" as key to retrieve the mocked object from the map.

2023-08-03 14:37 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +                    .thenReturn(new DBusPath("/mock/device/" + interfaceId));
```suggestion
            Interface mockedInterface = mock(Interface.class);
            mockedInterfaces.add(interfaceId, mockedInterface);
            
            DBusPath mockedInterfaceDbusPath = new DBusPath("/mock/device/" + interfaceId);
            
            when(this.mockedWpaSupplicant.GetInterface(interfaceId))
                    .thenReturn(mockedInterfaceDbusPath);

            doReturn(mockedInterface).when(this.dbusConnection).getRemoteObject("fi.w1.wpa_supplicant1",
                    mockedInterfaceDbusPath, Interface.class);

```

2023-08-03 14:38 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
> +    }
```suggestion
    private void thenScanIsTriggered(String interfaceId) {
        verify(this.mockedInterfaces.get(interfaceId), times(1)).Scan(any());
    }
```

2023-08-03 20:20 UTC, mattdibi approved these changes
LGTM 👌

2023-08-04 13:18 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/NetworkStatusService.java
> +     * identifier is typically the interface name. For the modems, instead,
Use id instead of name.

2023-08-04 13:20 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/NetworkStatusService.java
> +     * identifier is typically the interface name. For the modems, instead,
In the javadoc:

```
@param recompute
     *            If set to true, the NetworkStatusService will perform some additional **expansive** operations (like AP
     *            scanning) to ensure the status returned by the method is up to date. If set to false, it will return
* the status as returned by the network configuration provider.
```

do you mean expansive or expensive?

2023-08-04 13:58 UTC, pierantoniomerlino commented
It seems that in https://github.com/eclipse/kura/blob/0beca995f07c92427b4cc504dfc0bb64c83966d2/kura/distrib/src/main/resources/common/manage_kura_users.sh#L145 a space is missing. This prevents the scripts to run correctly.

2023-08-07 14:46 UTC, pierantoniomerlino approved these changes

2023-08-07 14:46 UTC, merged