feat(web2): WPA2 Enterprise (802.1x) frontend support
eclipse/kura pull request #4821
Opened 2023-08-28 12:10 UTC by GregoryIvo

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped

**Screenshots:** If applicable, add screenshots to help explain your solution

**Manual Tests**: Optional description of the tests performed to check correct functioning of changes, useful for an efficient review

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2023-08-28 12:12 UTC, GregoryIvo commented
GWT
- [x] tab creation
- [x] basic UI elements
- [ ]  populate help fields
- [ ] fix bug when storing settings in meta type
- [ ] fix meta-type retrieval
- [ ] hide and show tab when Enterprise is selected
- [ ] hide enterprise in AP mode
- [ ] add fields for certificates and support for other security types

2023-09-06 13:18 UTC, marcellorinaldo requested changes

2023-09-06 13:18 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/NetworkTabsUi.java
> +        insertTab(this.net8021xTabAnchorItem);
We should show the tab and insert the anchor item only if we are on generic profiles that have `NetworkManager`, i.e. only if `this.isNet2` is true. Look at the `updateTabs()` method.

2023-09-06 13:25 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
> +netWifiWireless8021x=802-1x
Remember to update also the japanese version of this file.

2023-09-06 13:25 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/GwtWifiSecurity.java
> +    netWifiSecurityWPA2WPA3Enterprise,
Please update copyright header

2023-09-06 13:25 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/Gwt8021xInnerAuth.java
> +package org.eclipse.kura.web.shared.model;
Please add copyright header.

2023-09-06 13:25 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/Gwt8021xEap.java
> +package org.eclipse.kura.web.shared.model;
Please add copyright header.

2023-09-13 12:15 UTC, GregoryIvo commented
closed in favor of: https://github.com/eclipse/kura/pull/4852

2023-09-13 12:15 UTC, closed without merging