feat: Container Orchestration and Triton Container service improvements
eclipse/kura pull request #5121
Opened 2024-02-09 15:28 UTC by pierantoniomerlino

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

This PR improves the `ContainerOrchestrationService` and `TritonContainerService` exposing the following options:

- runtime: set the runtime used by the container engine
- devices: set a list of devices to be passed to the container
- backend path: set the backend folder for the Triton server.

2024-02-09 15:55 UTC, MMaiero commented on kura/org.eclipse.kura.ai.triton.server/OSGI-INF/metatype/org.eclipse.kura.ai.triton.server.TritonServerContainerService.xml
> +            description="Specify the path on the filesystem where the backends are stored.">
```suggestion
            description="Specify the filesystem path where the backends are stored.">
```

2024-02-09 15:55 UTC, MMaiero commented on kura/org.eclipse.kura.ai.triton.server/OSGI-INF/metatype/org.eclipse.kura.ai.triton.server.TritonServerContainerService.xml
> +            description="Specify the runtime the Triton container can use."
```suggestion
            description="Specifies to the Triton container the runtime to use."
```

Would it make sense to update the descriptions with some examples?

2024-02-09 15:55 UTC, MMaiero commented on kura/org.eclipse.kura.ai.triton.server/OSGI-INF/metatype/org.eclipse.kura.ai.triton.server.TritonServerContainerService.xml
> +            description="Specify the devices the Triton container can use as a comma separated list of device paths."
```suggestion
            description="Specifies, as a comma separated list of device paths, the devices that the Triton container can use."
```

2024-02-12 07:59 UTC, mattdibi commented on kura/org.eclipse.kura.container.provider/OSGI-INF/metatype/org.eclipse.kura.container.provider.ContainerInstance.xml
> +            description="Specify the runtime the container can use."
Specifies the fully qualified name of an alternate OCI-compatible runtime, which is used to run commands specified by the "run" instruction. Example: "nvidia" corresponds to "--runtime=nvidia".

2024-02-12 08:00 UTC, mattdibi commented on kura/org.eclipse.kura.container.provider/OSGI-INF/metatype/org.eclipse.kura.container.provider.ContainerInstance.xml
> +            description="Specify the runtime the container can use."
I would add a little bit more details here... something like:

```suggestion
            description="Specifies the fully qualified name of an alternate OCI-compatible runtime, which is used to run commands specified by the 'run' instruction. Example: 'nvidia' corresponds to '--runtime=nvidia'."
```

2024-02-12 08:06 UTC, mattdibi commented on kura/org.eclipse.kura.container.provider/OSGI-INF/metatype/org.eclipse.kura.container.provider.ContainerInstance.xml
> +            description="Specify the runtime the container can use."
Also: does this work with Podman? Docker expects fully qualified names, Podman seems[ to only accept paths](https://docs.podman.io/en/latest/markdown/podman-farm-build.1.html#runtime-path)

2024-02-12 08:08 UTC, mattdibi commented on kura/org.eclipse.kura.container.provider/OSGI-INF/metatype/org.eclipse.kura.container.provider.ContainerInstance.xml
> +            description="Specify the runtime the container can use."
Nevermind, I was looking at the wrong docs: https://docs.podman.io/en/latest/markdown/podman.1.html#runtime-value

2024-02-12 08:20 UTC, mattdibi commented on kura/org.eclipse.kura.ai.triton.server/OSGI-INF/metatype/org.eclipse.kura.ai.triton.server.TritonServerContainerService.xml
> +            description="Specify the filesystem path where the backends are stored.">
I think we should point out that this *overrides the backend stored within the container* with the backend found on the host filesystem. This behaviour is quite nuanced. Could be something like:

```suggestion
            description="Specify the host filesystem path where the backends are stored. If left blank, the backends provided by the Triton container will be used.">
```

2024-02-12 08:29 UTC, mattdibi commented on kura/org.eclipse.kura.ai.triton.server/src/main/java/org/eclipse/kura/ai/triton/server/TritonServerContainerManager.java
> +        }
I'm not sure you actually need this: if I understood correctly you're mounting the host path where the Triton server already expects its backend folder. 🤔

2024-02-12 08:38 UTC, mattdibi commented on kura/org.eclipse.kura.ai.triton.server/src/main/java/org/eclipse/kura/ai/triton/server/TritonServerContainerManager.java
> +        }
I would say that the best approach is to stay consistent with what we already have (i.e. `TRITON_INTERNAL_MODEL_REPO` approach). Therefore this is ok as-is.

2024-02-12 08:45 UTC, mattdibi commented on kura/org.eclipse.kura.ai.triton.server/OSGI-INF/metatype/org.eclipse.kura.ai.triton.server.TritonServerContainerService.xml
> +            description="Specifies, as a comma separated list of device paths, the devices that the Triton container can use."
```suggestion
            description="Specifies, as a comma separated list of device paths, the host devices that the Triton container can use."
```

2024-02-12 08:53 UTC, mattdibi requested changes
LGTM but I pointed out a couple of places (mainly in the parameter description) where some more details might be needed.

2024-02-12 09:56 UTC, mattdibi approved these changes

2024-02-12 10:31 UTC, merged