fix(web2: Added better error message for password never set
eclipse/kura pull request #5163
Opened 2024-03-04 15:09 UTC by salvatore-coppola

Added better error message for password never set for the wifi configuraiton

2024-03-04 15:25 UTC, marcellorinaldo submitted a review, later dismissed

2024-03-04 15:32 UTC, marcellorinaldo requested changes

2024-03-04 15:32 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
> +passwordNeverSetError=The password for this configuration has never been set. Please set it and apply the configuration again.
Please add JAP version too

2024-03-04 15:37 UTC, salvatore-coppola commented on kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
> +passwordNeverSetError=The password for this configuration has never been set. Please set it and apply the configuration again.
> Please add JAP version too

well my Japanese is a bit rusty :P

2024-03-05 08:05 UTC, marcellorinaldo commented on kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
> +passwordNeverSetError=The password for this configuration has never been set. Please set it and apply the configuration again.
Just use google translate

2024-03-06 08:16 UTC, marcellorinaldo approved these changes

2024-03-08 16:09 UTC, merged