refactor(api): Removed bluetooth old api, implementation, tests and examples
eclipse/kura pull request #5323
Opened 2024-07-24 11:00 UTC by pierantoniomerlino

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

This PR removes the Bluetooth Old APIs, their implementation, the tests and examples. In particular, the following packages are deleted:

- org.eclipse.kura.bluetooth
- org.eclipse.kura.bluetooth.listener
- org.eclipse.kura.linux.bluetooth
- org.eclipse.kura.example.ble.tisensortag
- org.eclipse.kura.example.beacon
- org.eclipse.kura.example.beacon.scanner

2024-07-24 12:26 UTC, mattdibi requested changes
Whoops! Build fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (get-kura-bundles) on project distrib: Unable to find artifact. The following artifacts could not be resolved: org.eclipse.kura:org.eclipse.kura.linux.bluetooth:jar:2.0.0-SNAPSHOT (absent): Could not find artifact org.eclipse.kura:org.eclipse.kura.linux.bluetooth:jar:2.0.0-SNAPSHOT in kura_addons (https://raw.github.com/eurotech/kura_addons/mvn-repo/)
```

2024-07-24 12:28 UTC, mattdibi commented
Also: is this a breaking change?

2024-07-24 12:33 UTC, pierantoniomerlino commented
> Also: is this a breaking change?

I don't think so... we're removing stuff that has been already deprecated.

2024-07-25 13:02 UTC, mattdibi approved these changes
![image](https://github.com/user-attachments/assets/65c9b5ec-d7e7-4e8e-867a-ba8d31ca5465)

2024-07-25 13:07 UTC, merged