feat: modemManager based position provider
eclipse/kura pull request #5471
Opened 2024-10-21 08:28 UTC by sfiorani

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped

**Screenshots:** If applicable, add screenshots to help explain your solution

**Manual Tests**: Optional description of the tests performed to check correct functioning of changes, useful for an efficient review

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2024-10-31 08:35 UTC, mattdibi commented
@sfiorani please add a description for this PR

2024-10-31 16:48 UTC, pierantoniomerlino requested changes

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/ModemManagerDbusWrapper.java
> +    private static final String MM_DEVICE_NAME = "org.freedesktop.NetworkManager.Device";
Both `NETWORK_MANAGER_BUS_NAME` and `MM_DEVICE_NAME` are not used.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/ModemManagerDbusWrapper.java
> +    private static final String MODEM_MANAGER_BUS_NAME = "org.freedesktop.ModemManager1";
Following the convention already used in this class, the name should be `MM_BUS_NAME`

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/ModemManagerDbusWrapper.java
> +    }
Please use the constant already defined for the Modem path.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/ModemManagerDbusWrapper.java
> +                Properties.class);
Also here.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
> +        this.getEnabledModemsPaths().stream().forEach(modemPath -> {
I think that you can use the `forEach` method directly to the List, without using `stream()`

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMLocationParser.java
> +    private int m3Dfix;
This field is not used or assigned.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMLocationParser.java
> +    private char validFix = 0;
These three fields are assigned, but not used.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMLocationParser.java
> +        } catch (Exception ex) {
Here you catch all the exceptions, but the code above does not throw anything. Do you implemented this for catching the unchecked exceptions, like the `NumberFormatException`?

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMPositionProvider.java
> +    private static final Logger logger = LoggerFactory.getLogger(MMPositionProvider.class);
This logger is not used

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMPositionProvider.java
> +    private DateTimeFormatter nmeaDateTimePattern = DateTimeFormatter.ofPattern("ddMMyy hhmmss");
Also this one is not used.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMPositionProvider.java
> +/*******************************************************************************
Please run the clean up to this class.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMPositionProvider.java
> +    }
It is supposed that the `init` method is called before the `start` one. But what happens if this is not done? The `refresh` field is initializated to 0 and the schedule throws an `IllegalArgumentException`. Maybe it is better to add a check of this variable before using it.

2024-10-31 16:48 UTC, pierantoniomerlino commented on kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMPositionProvider.java
> +
The `gpsDeviceAvailabilityListener` is not used here. Is it correct?

2024-11-04 13:57 UTC, MMaiero commented
![image](https://github.com/user-attachments/assets/ecf7b113-c342-41b6-bb43-c1909ef16dc5)

@sfiorani

2024-11-04 16:45 UTC, pierantoniomerlino approved these changes

2024-11-04 16:46 UTC, pierantoniomerlino commented
@MMaiero the Sonar analysis failed, but @sfiorani only renamed the files. I think that we shouldn't take care of this refactor in this PR.

2024-11-04 16:49 UTC, merged